# Louise

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2025-04-21 | Guidance to add spatial registration to shiny app. | spatialLIBD::app_server seems to be breaking for layer_stat_cor_plot when retriving colors, this looked more like an issues with the spatialLIBD code than the users application. Will investagate further |
| 2025-04-18 | ways to explore domain specific marker genes compared to other domain genes | Researcher is Intrested in definind what makes a spatial domain unique from the others. I recomended to review the top enrichemnt and parwise genes from the modeling results. Running MeanRatio may also be informative. I also recomended reviewing litature to see if there is any other work that may help caracterize this domain. |
| 2025-04-08 | i have a question about visualization: when i calculate the logcounts matrix of the pseudobulked SRT data, i get some negative values because there are some extremely low counts. under the hood, the function is using edgeR:cpm() by adding an average count of 1 (https://github.com/LieberInstitute/spatialLIBD/blob/35fe720741b0bf44e19475f80b5f3475f347d6b6/R/registration_pseudobulk.R#L163). i think this is fine for DE analysis, but it is hard to interpret when visualizing boxplots of gene expression on the log scale. i tested this out on the DLPFC n=30 SRT data as well, and i also get some negatives when lognormalizing the pseudobulked matrix.
what is the preferred way to visualize this? one option would be to just leave the negatives as is. another option would be to add a slightly larger prior count, like 3, to prevent negatives while preserving the distribution of the data. | The negative values are probably 0s in the counts matrix, I agreed that the negative values in vaisualizations are tricky to expain, it would be more intutaive if they were also zeros. I am not sure if changeing the prior.count to > 1 would help. I suggested plotting the pseudobulk counts as a sanity check and exploring the count values that end up as negtive in logcounts. Researcher may leave an issue on spatialLIBD about this. |
| 2025-04-02 | Review scripts containing pseudobulk visium data to compute DEG data. | We debugged code for pseudobulkDGE, we found several silent errors that were leading to empty output, but not errors. After correcting some of the variables we got closer to expected output, but still need to further debug. I think the function could be improved, prehaps we'll create a github issue |
| 2025-03-19 | Reviewing code to quantify mRNA expression | Feedback on how to document code for working with HALO/RNAScope data. From example scripts I think it would be best to build an R package. I provided some examples of what that looks like. They are also thinking a shiny element would be good, that adds additional, but managable, complexity. |
| 2025-03-13 | I'm trying to use the spatialDLPFC_snRNAseq dataset from spatialLIBD. I'm not sure how much QC has been done. I'm also wondering what the UMAP was run on. | We reviewed the key details for the spatialDLPFC snRNA-seq data. Key colums are cellType_layer, and cellType_broad_hc, also dropping sce$cellType_hc == "Ambiguous". I noted our documentation for fetch_data() could benifit from more details about this dataset. |
| 2025-03-05 | registration wrapper debug | we worked on filling the rowData of a sce object after converting from seurat, as the gene ids are key for running layer_stat_cor later in the spatial registration process |
| 2025-01-30 | discuss about writing methods | Demoed how to use sciwheel and cross ref in google docs for witing paper |
| 2025-01-28 | Issue with several plots in a  PDF file | We found that par does not interact well with patchwork plot objects. To arrange a list of patchwork objects in to 4 rows use Reduce("/", plot_list) |
| 2025-01-24 | setting goals for the year- to complete paylocity profile | We discussed strategies set qunatiative goals, such as number of presentations or breaking large projects in to individual, completable steps |
| 2025-01-15 | identifying files in MDDseq project | We revieded the project history and  orgainzation to help find needed scripts |
| 2025-01-06 | I am doing DEG analysis on DLPFC PNN project, I got CAMK2A as the top upregulated DEG in neuropil+ spots. But when I plot the expression of CAMK2A in neuropil+ vs neuropil- spots as bar plot, the bar in neuropil- category is higher which contradicts the DEG result. | Tools like scater::ploExpression or DeconvoBuddies::plotGeneExpress() will help plot gene expressio vs. catagorey. jafflab::cleaningY() will regress out varaibles controled for in DEG and provide the best representation of what the "model" sees. We could consider adding the "clean" expression as an assay durring the "modeling" pipeline from spatialLIBD. |
| 2024-12-19 | Git pull fails | debugging git pull with conflicts |
| 2024-12-04 | discuss about qtune results, spatial registration script. completed running add clusters and model psuedobulk | Review results from q-tune, looks like it might not align with the desired resolution for the data. Review output from modelining analysis. |
| 2024-11-27 | Discuss about next steps spatial registration, Rscripts. | Set up dataset for spatial registration, review code, plan for how to interpret output |
| 2024-11-22 | Running BayesSpace, can we go over the preparatory steps | We discussed the quality control, feature seelction, and batch corrections steps needed before clustering visium data |
| 2024-11-01 | debug deploy.R | We comapred the app.R and deploy.R scripts to working ones, corrected some issues with the here function. This did not succesfully deploy the app (local version works). Likewise we matched the settings to the ERC spp settings, still failed to run. We may need a second set of eyes to help finetune the shiny.io settings or diagnose the issue here. |
| 2024-10-31 | BayesSpace clustering | We discussed the steps needed to prepare for spatial clustering: quality control, normalization, feature selection, demension reduction, batch correction THEN clustering w/ BayesSpace. We went over the clustering code from LFF ERC |
| 2024-10-18 | Merging HALO data | Discussed tips for working with HALO data, and how to visualize |
| 2024-10-02 | spatial registration, Automatic annotation of spatial registration results, spatialLIBD cluster import()/export() | Reviewed the spatial registration pipeline: pseudobulking, modeling, correlation, and annotation |
| 2024-09-23 | facing issues with cyberduck - it keeps asking me for the authentication key always | Trouble shot cyberduck so login works automatically with ssh keys |
| 2024-09-16 | Can you please point me to a table (from Maynard et al. 2021, Huuki-Myers et al. 2024, or other?) that lists the necessary marker genes important for delineating each cortical layer (WM, layer 1-6) in clustered 3’ Visium DLPFC datasets? | Pointed to the different ways we have to access modeling data from the fiffernt DLPFC studies |
| 2024-09-06 | using GitHub to sync laptop & JHPCE | Setting up and testing github access on laptop and JHPCE, continued |
| 2024-09-05 | using GitHub to sync laptop & JHPCE | Setting up and testing github access on laptop and JHPCE |
| 2024-08-28 | Manisha Training- Laptop config: Cyberduck | We setup cyberduck and ssh keys for the new laptop |
| 2024-08-12 | we find that we have thousands of upregulated DEGs and the volcano plot looks odd. We are following the code in the best practices st book and am not sure if the plot we are getting is just the nature of the data and this brain region, or something about how we are running the DEG testing | NA |
| 2024-07-31 | I have questions regarding the leafcutter pipeline, which is used in the MDD project to produce the clustered files. | We walked thorught the code for leafcutter and the output for each stage |
| 2024-07-18 | spatialLIBD app results and interpretation for pseudobulk specific bayes space k | We de-bugged some issues with launching the app, and made some observations about the clustering at different ks, utimatley the optimal k will be based on the biological question at hand |
| 2024-07-15 | single cell markers | We discueed MeanRatio and 1vAll methods for finding marker genes |
| 2024-07-11 | I am using spatialLIBD::registration_wrapper() for enrichment DE testing. The dimensions of my spe are 29720 x 77553, but the modeling results only represent 12326 genes. I'm not sure what happens to the remaining genes or if this behavior is intentional (because not all the genes have significant adjusted p-values). Why do all the modeling types result in the same number of genes? | registation wrapper filters the pseudobulked object,dropping lowly expressed genes. Often resutlsing in ~12k genes (comapred to ~30lk genes in the original object). This is expected behaviour. |
| 2024-06-26 | Spatial-Registration workflow. I am particularly confused with the use of the reference, as it is coming from DLFPC | We discussced refernce vs. querery in spatial registation and the required modeing to prep the data for the registration anlaysis. |
| 2024-06-03 | Review the habenula snRNA-seq data to assess the enrichment of habenula DEGs for fentanyl administration in cell type-specific marker genes | Identified the correct data and organization for this analysis |
| 2024-05-14 | Questions about article | We discussed the spatialDLPFC paper, how we integrated the sn and visium datasets |
| 2024-05-13 | deconvolution results (cell type proportions) to be used as covariates for differential expression analysis in Brainseq DLPFC, caudate and hippocampus | We have old results for the brainseq DLPFC, but i described the method we chose from deconvolution benchmark to get most accurate deconvolution results |
| 2024-05-05 | steps to make heatmap for domain-wise enriched significant marker genes | We walked through the process of creating heatmaps with ComplexHeatmaps for marker genes, selecting and annotating genes, subsetting logcounts, creating annotations for sampels and genes |
| 2024-05-01 | Basic stuff to run R scripts in the cluster | We discussed tools to manage files on JHPCE, and stradagies to get code to the cluster (either edit remote code, or use git) |
| 2024-04-29 | Making RNAscope plots using HALO csv files | I showed the three kinds of plots we made for the habenula RNAScope data, geom_hex/stat_summary_hex for continuious variables across the tissue, geom_rect for specific cells, and geom_rect + geom_point for highlighting rare cell types. |
| 2024-04-28 | Help finding odds ratios for PGC3 SNPs to determine risk allele, and general discussion about plot results and aesthetics | We double chekecked the stats for eQTL results, refined results and plots accordingly |
| 2024-04-25 | Understand how to run a MAGMA analysis for habenula DEGs | I walked Daianna through the 3 steps of MAGMA, and the needed input from GWAS data and gene sets. There are many detials to consider, especally in preparing this data. Daianna will start with preparing the GWAS data and we will revisit the next steps. |
| 2024-04-25 | We want advice as to *how best* to do the deconvolution | We talked thorough their proposed analysis. THery Decided Bisque may be the test boption I pointed them to my tuttorial for Bisque Bisque https://research.libd.org/DeconvoBuddies/articles/Deconvolution_with_Bisque.htm |
| 2024-04-01 | feedback on figures | We discussed tools for spacing and aligning objects in BioRender. I suggested maximizing font sizes and reducing white space |
| 2024-03-27 | access bulk RNAseq from samples cataloged in the Lieber-internal bulk rnaseq database | Able to access the data throught the LIBD dataportal, I also pointed to the combined LIBD rse_gene in brain_swap (which I think might be the source of the portal data...would need to check) |
| 2024-03-23 | slurm job loops | Re-organized code to run with a shell script from slurm_jobs. We solved a bug with args index, and talked about adding catches for unexpected inputs. Future goal is to use map to replace for loops when handling list of data objects |
| 2024-03-14 | I tried to apply "qSV_model_DE_analysis.R" in lithium-exposed samples ( from Dpseq data), but I was confused by some of the code, especially "run_DE.R." | I walked throught the run_DE function I wrote for MDDseq (a wrapper for the limma-voom) pipline. I pointed out what parts of the MDDseq code that could adapted and simplified for this use case (its less complicated than the many DE runs we completed for MDDseq) |
| 2024-03-11 | quick big fix. Its the same eQTL code -- just one header in a file that's always missing | Having some conectivity issues with JHPCE, so we didn't get a full bug fix in I suggested some de-buggin strategies  [Update 3/15] We met again breifly to confirm the functions were working as intended. Initial issue was caused by un-intentinally overwriting the function |
| 2024-02-28 | Deconvolution | Giovanna and Jisu are working with some bulk RNA-seq data as a some pilot data in a new brain region prior to preforming saptail. They want to use deconvolution to help QC the samples, selecting for good disections. I walked them through our current recomndations for deconolition to help with this goal. |
| 2024-01-25 | making a corrplot with a lot of data points . | Sreya wants to compare the correlation of 5 transcipts with 2k degradation transcripts. She had the data in the right format but needed help appllying the cor function to the table using group_by. Corrrplot was not the correct function for what she wanted to achive here. |
| 2024-01-22 | Maybe divinding them by sample name may help. | Michael and Peter are working on a BPD vs. MDD DE analysis. They were getting more DEGs than were reported in an early version of the MDDseq project. I could not find the code for the data they were refrencing, with out the code it will be impossible to diagnosis what is differnt in the two analysis. I recomended they use the more up to date data from MDDseq, and pointed them to the correct data & scripts. |
| 2024-01-22 | when I try to rerun R dreamlet pseudobulk on the new JHPCE, I keep getting errors... (provided code example) | Tricia and Fernando are re-running serval analysis they previously had working on the sge cluster, with the update to slurm they are now having issues. They are also having differnt errors in the same scrips + data. This could be a multi-facet issue, but firstly sounds like a R package version issue. I advisded the first step should be to have the same set-up, work in the same version of R and the same version (most updated) packages. See what errors persist and go from there. I also recomended Frenando start using git repos and version control with his team to help keep projects organized and consistent. |
| 2023-11-30 | Regarding the transcriptome assay from the multiome approach, I have selected canonical gene markers from the different samples; Moving further, I would like to integrate to the analysis external gene-markers shared by S.Page. I am looking the best way to do this. | Researchers are starting the annotation/cluster integration of the multiome data. The data is currently clusted indiviudally by sample, sn, ATAC only, and combined sn+ATAC. findMarker has be used to calc marker stats for each cluster in each sample (there is a ton of data to digest). I am unfamilar with the sample independent cluster, consered marker gene integration from seurat. But I gave advice to check the current clusters for high expression of any of the known marker genes to see if we're picking up the expected biological signal, and do some prelimary annotations as a sanity check. Also to keep following the workflow and see if the conserved marker genes match with any of the know markers. Also to start recoring annotations for the clusters in a csv file for easy editing by hand as well as easy reading in to R |
| 2023-11-29 | Help with qSVA overview schematic | I advised on how to adress some issues with the qSVA overview plot, both minor issues like aliginig and resising objects with biorender tools, and major rearngment of the table and DE application part. |
| 2023-11-15 | I would like to discuss with you the correlation issue related to the cellular_component model of the qsvaR package and get your feedback. | Adressing feedback on some unexpected behavior from qSVAR package. The qSV values show no significant correlation with other phenotype metrics (they have in the past), while this is not impossible it is strange. There are many factors that could have lead to this issue. We talked about some debugging strategies, starting with re-running the workflow on familar data to see if we can re-create the issue or detirmine if it is unique the external dataset. |
| 2023-10-25 | Hi! We would love an opinion on our (now cell-type assigned) single nuclei rna-seq data, i.e. how they look - if anything is off, advice for improvement... | This data has one cluster that is unqique to one donor, post batch correction. This donor also has some unique clinical background as well, I advised to drop the cluster as their batch corection seemed to be correct, and it possible that this is a rare biologically real cluster but there is not enough data to confirm. |
| 2023-10-19 | Help migrating to SLURM setup | I walked through the new login commands for SLURM + updating his bashrc file so they can work with the slurm cluser |
| 2023-10-12 | Prepare expression bed files for tensorQTL | Adapted mode code for tensorQTL prep, had to add genomics ranges to the sce object, and deal with bugs around rse_to_bed function |
| 2023-10-05 | Prepare covariate input files for tensorQTL | Worked through addapting code for tensorQTL prep for the MDD single cell data - had to deal with bugs relating to cell type names |
| 2023-09-29 | Interpretation of results plotted in inflection plots of Cellranger-arc data sets (GEX assays). For example, how do you know which genes are representing neurons or glia? | We looked at the rank vs. total UMI curves relevant for emptyDrops for the atac-seq samples. We have discussed these samples before. We went over how the emptyDrops function works again and what we can guesss is happening in the curve (neurons vs. glia vs. empty droplets).  There is concerned beause for the 42-4 sample the wetbench target number of nuc was 7k, emptyDrops retrurns 9k. I thought that that sounded in the right ball park |
| 2023-09-22 | help get normalized single cell data from a single cell rse for downstream eQTL | I helped modify my code for creating input files to work witht the new pseudobulk data. We got the gene PCs done, he needs to get the genotype files together for this data before we can move to the next steps. Planning to meet more next week to continue this process. |
| 2023-09-21 | Discuss deconvolution for some future work | They were interested in running deconvolution on the bulk MDDseq with the new large MDD snRNA-seq dataset. The MDD snRNA-seq dataset is only sACC, we concluded that only haveing one region might make this analysis a bit awkward for the Amyg data. I them to the current deconvolution results and how we applied those results in downstream analysis. |
| 2023-09-21 | help get normalized single cell data from a single cell rse for downstream eQTL | I walked through using registration_pseudobulk() on the large MDD single cell dataset and went over how the function works. We are planning to meet agian to go over running PCA to prep for eQTL analysis. |
| 2023-09-06 | snRNAseq celltype grouping in DLPFC data | I discussed diagnosing marker quality for the spatial hypocampus project. They are on the right track, and have created violin + hockystick plots for the different iterations of the dataset. I advised they elimate a noisy cluster and re-compute markers. |
| 2023-08-21 | I performed the whole analysis as previously established and also made an alternative version based on knowledge of OSCA book for single nuclei (with adaptive thresholds for QC and less tolerance for mito UMIs). Would you help me checking my QC thresholds and seeing if they make sense? | Used MAD cutoffs on total UMIs, genes detected, mito %, and a metric we haven't worked with yet: genes per UMI. They evaluated the data all together (not by sample) and chose #Mads by what seemed reasonable. The values  used look good, but perhaps a bit strict. We looked at the distributions, which are slightly different between samples, I advised to use scater::isOutlier to see what the cutoffs would be by sample. One step lacking is doublet detection, I suggested to apply scDblFinder::computeDoubletDensity. The dataset already has clusteres and is annotated  (lots of work) I suggested that a great double check is to calcluate the median value of the QC metrics for each final cluster and see if any are much higher than the others as a good double check that his initial QC process worked well. |
| 2023-08-10 | writing tweets efficiently | I gave some pointers about writing tweets. Mostly keep it simple, give people a call to action "check out this link!", add something eye catching. Also to spend sometime reading tweets and pay attention to what you like that other people tweet? What caught your interest? We also talked some stradgedy about tweeting around confrences, calling peoples attention to your talk/making it easy for people to find you to get in touch |
| 2023-08-09 | Running DeconvoBuddies on the Mathy's data | We talked thorough the thigns to think about for the Mathy's dataset (this dataset has case + control paitents and found DEGs w/in cell types). I advised to start simple with the broad cell tytpes and not consider Dx at first. Check if the DEG they idetified are in our marker set. I think this will need some discussion with the project team if Dx is a concern for spot deconvolution. |
| 2023-07-26 | Feeback on spatial data + code organization | We took a look at the changes in the clustering in the spatial data before and after cropping out a area of questionalble quality. To me it looks like the QC params are too strict leaving spots floating in space, which I'm guessing is contributing to weird BayesSpace results (but this is a guess). We also talked code organization strtagedy - mostly keep it simple and consistent |
| 2023-07-26 | Feedback on workshop vignette | I helped improve the formatting & content for a BioC qSVA workshop, main feedback ins to focus on and highlight the qsvaR steps in the workflow (rather than SummarizedExperiment overvew & DEG analysis) |
| 2023-07-25 | Practice BioC talk | I helped review a practice BioC short talk, Mostly the talk needs to give more slides to discussing the results & include more actual plots not just icons (this is much improved this presentation for the 7/26 meeting :) ) |
| 2023-06-28 | About empty drops run with GEX cellranger-arc data | DropletUtils::emptyDrops on the two LIBD + two example samples has been run. We first clarified some terms and outputs she had recorded. For the most part DropletUtils returns similar number of non-empty cells as CellRanger arc, but didn't confirm that the two methods flag the same cells. I recomended to create a confision matrix between the two methods for each sample to check this.  The main concern  has is the LIBD sample with only  3k cells input, has 9k non-empty droplets returned by emptyDrops. This is quite odd as the CellRanger Arc metrics look quite bad for this sample, but the DropletUtils metrics look fine (there are high UMI values for many droplets). We will want to dig in to this more to understand the differnces between the two methods. |
| 2023-06-15 | 1/Learn about the roxygen2 syntax for examples. 2/Run devtools::document() like in dev/04_update.R (maybe also auto-style code). 3/Edit the news.md file + bump version on the DESCRIPTION (and change the date). 4/Learn about how to sync her local repo with steps like http://contributions.bioconductor.org/git-version-control.html#new-package-workflow (aka register to https://git.bioconductor.org/BiocCredentials/login/?next=/BiocCredentials/ like @Daianna González + add the upstream remote + git push to both upstream and origin). | We started with getting github token access for their laptop working. Then started a pull request using usethis for qSVA, for them to add seed capabilities to several functions. We will need to meet several more times to complete the whole help request |
| 2023-06-14 | I created this github repo: https://github.com/LieberInstitute/neurovasculature-pilot/tree/main. Also, integrated it with slack, but instead of integrating the main branch, I linked the devel branch, and I am unable to see the commits that I make on slack. They are updated on github, though. So, I need help with the integration. | they mentioned that they had to login everytime she pushed a commit from the directory in question (but not other repos). I thought we should start by using a github access token to update her login to github from JHPCE. The best way I know how to do this is to use gitcreds::gitcreds_set() in R. At first it gave us an error, which was solved by adding the git modules loaded in the team bashrc to theur basrc file as well as their .gitconfig file. After that we were able to save the token to their JHPCE setup and the github push issue seemed to be solved |
| 2023-06-08 | Options for cell type specific eQTLs | Reviewed input for tensorqtl (it is counts, not logcounts), and revised what how we filter lowly expressed exon-exon junctions using http://research.libd.org/jaffelab/reference/expression_cutoff.html. |
| 2023-05-09 | Overfitting in qSVA | The researcher was concerned about the large number of variables in the reproducibility DE experiment, specifically the PC. I pointed out that the point of the anlaysis was to test the effectiveness of the models (with and without qSVs) so while this might be a valid concern in a sperate DE analysis, we are testing model quality here. I also noticed that the reproducibility anlaysis was not using functions from the qsvaR package, and that as qsvaR is the "product" of this whole project its important we use the functions in this anlysis . |
| 2023-03-24 | tensorQTL code overview | We went over the code I previoulsy wrote for tensorQTL, and some of the custom functions for preparing the input data. How to input the different datatypes in to python, and run the function, and strategies  for running the different cell types in parralell on the GPU queue |
| 2023-03-23 | Check some issues with GitHub Actions | I helped decipher an error message they got in the BioC check in the GitHub Actions involving a local path harcoded in to one of her tests. We also debugged for similar issues by searching her code for other local paths that would cause her code  to break when run remotely |
| 2023-03-20 | tensorQTL pipeline overview | I shared the tensorQTL example I presented at rstats club. We also went over the different in-puts and formats, including some we can re-use from bulk MDDseq. WE also discusses the differnt setting for tensorQTL and how to adapt sh files to submit to the GPU queue |
| 2023-03-01 | Deconvolu code where the bisque doesnt show any differences | Researcher was having some issues with functions from DeconvoBuddies, namley plot_marker_express. I am going to check that on my end as it seems like the computer wasn't finding the support functions for the main function. They were also having trouble matching the gene names between the sce and bulk rse objects, the ensembl names seemd to have differnt versions, I advided to maybe switch to using the gene symbols to keep things simple. |
| 2023-02-21 | Creating marker heatmaps with pseudobulk data | We went over the ratioinal behind psuedobulking and how we can use heatmaps to show marker experssion. Created psuedobulk data for three different clustering methods, and went over the basic process of making heatmaps. Bukola will work on the aestetics of the heatmaps, and cerate one for all thee clustering methods. |
| 2023-02-17 | Setting up .bashrc file for folder access permission for DLPFC-SCZ project | related to my meeting with Uma on 2/10. We fixed Boyi's bashrc to allow group write by deafult, fixing the ,git issue and eliminating the need to re-run the permission update script often |
| 2023-02-10 | I have questions on GitHub and submitting SGE jobs. | Researcher was having file permission issues, the group permissions for several files in a shared project were set to read only. This was causing issues with the team using scripts but also in making git commits as some of the idex files in .git were read-only. We updated her bashrc files to contain "umask u=rwx,g=rwx,o= ## equivalent to umask 007" to prevent this in the future and ran the premissoin update script. |
| 2023-02-09 | Moving forward with multiple cluster methods | Researcher hads run muliple clustering methods on the habenula data, I advised to pick the two that were the most simmlar to previous annotations (we were happy with) via rand index, and start examining marker gene expression. |
| 2023-01-19 | GitHub for a beginner | The researcher created a github account and I talked them thuogth the basics of git, But we hit a snag with the instalation of git on their laptop, git is built in to xcode in the ventura OS (which her machine is running) but she had some trouble with that instalation too. They're going to try and fix that independtly, and reach out if she needs more help gettign off the ground with git + github |
| 2023-01-18 | snRNA-seq GLM PCA | We adapted code from the DLPFC work and https://www.stephaniehicks.com/biocdemo/articles/Demo.html to run GLM-PCA to prep for batch correction |
| 2023-01-13 | snRNA-seq QC | We adapted QC code for the habenula data |
| 2023-01-11 | Plotting Gene Expression with SCE | Continuing work with the single cell mouse data, I pointed them towards scater::plotExpression to plot some of the genes her group is intested in observing by cell type. However we ran in to some bugs with running logNormCounts which we think is from an old version of R. I advised to update R and re-install the packages, hopefull that will fix the issue. |
| 2023-01-04 | Help building SCE with downloaded data | I helped them build a single cell experiment object with expression and metadata from an publication. Hopefully they can use this to independently explore the gene expression the group is interested in. |
| 2022-12-14 | Discuss Mean Ratio marker gene finding | Reasearcher wanted some background information about the deconvolution process we applied to the degradation data. I explained the mean ratio marker finding, the resulting stats, and how we used them to build our set of marker genes. Then the script for how we ran bisque + the output of bisque . |
| 2022-12-14 | Deconvolution study with rnaseq bulk data | Researcher wants to test if a gene of intrest to their group is associaited with a ceratain cell type. They are working with bulk mouse data. I suggested that deconvolution may not be able to answer the innital question but can provide depth to their bulk analysis. I suggested that they find a mouse single cell dataset that is relevant to their current data set, then first observe their gene of interest their, see if that answers any questions. Then they could use that data to run deconvioltion with bisque |
| 2022-11-30 | Understanding PCA for Habenula project | We discussed how PCA reduces the dimesions of our data and helps show the variance between samples. I helped strategize how to make PCA plots for the habenula data. Start plotting the first 5 PCs pairwise, color by Dx. Then explore key QC or demographic variables, see if we can indentify any patterns. I was unsure if this should repeat this for exon, jx, tx, as we didnt for MDDseq. But figured gene was a good place to start and if the other features should be explored too, the code should be easily adapatabe. |
| 2022-11-30 | Review deconvolition script for qSVA | I gave them a breif overview of the goals and process of deconvolution, including mean ratio marker finding. I linked my deconvolution slides. We then went over the code for running bisque on the qSVA dataset, including details of the input, refrence, and output data. |
| 2022-11-03 | help submitting jobs with R parallelization in jhpce. For instance, I would like to use scater::runPCA with the BPPARAM=BiocParallel::MulticoreParam(8)) parameter | Researcher is trying to run glmPCA on the very large MDD snRNA-seq dataset. They has a run submitted without parallelization that has been runing for 3 days. To try and speed things up she has been trying to use BioCparrallel, via MulticoreParam. But the scheduler keeps killing the job. We checked that -pe local X and MulticoreParam(X) match , so it wasn't that. I recomended to try to run a subset of the data to get a sense of how glmPCA uses memory. But couldn't come up with a fix to make the parallelization work. As its PCA it also can't be run as subsets, so there aren't other workarounds :( I think BioCparallel + sge scheduling would be a good topic for Rstats club as this seems to be a common headache |
| 2022-10-27 | I have this single nucleus RNA sequencing experiment with the mouse LS that Matt analyzed and we have a final single cell experiment, but I don't know how to do anything with this data set and want to learn how to plot heatmaps and possibly other things for this data set. Can we maybe schedule an hour to start this learning process and then I can schedule future time as needed? | Reseacher walked me through some plots they need for the LS paper: marker genes heatmap and expression violin plots. I pointed them to some code from DLPFC sn that should be helpful (they needs access to this repo). They also needs to get setup with JHPCE on their new laptop, I pointed them to the team laptop setup docs. They are also new to ggplot, so I pointed them to the visulization chapeter of R for data scientist. This will probaly require some follow up meetings |
| 2022-10-26 | Check the DEG heatmaps | Researcher has added a new color scheme to the heatmaps that makes the differnces between positive and negative more clear, how ever I think the darkest red being close to 0 is misleading, so they're going to fix that. I also recomended to simplify the annotaions on the combined heatmap so its easier to find and interpret patterns. |
| 2022-10-17 | Review TMM paper | We reviewed the reasons or correcting counts and why thats important for DE analysis. We went over the math behind TMM, and then how thoes ideas are used in edgeR. I pointed them to a stats quest video with a more detatiled explination of how the edgeR correction works. |
| 2022-10-14 | csvs that I want to merge together | Researcher showed me the csv files that he exported from different moduled on HALO. They seem to have the same rows, so copying the needed column in to a differnt csv is easy in excel (where they are working) but I showed that how to check that things are really aligned with some excel functions. We also looked at the data in prism, which I had to quickly learned about. I advised to should show the data in boxplots not as a barplot to better display that data, and went over the checks for running an anova. |
| 2022-10-11 | GO and KEGG boxplots with the modifications you suggested | Researcher showed me their dot plots with the correct 0.05 q val filter, they looked good, ready for discussion. One tweak , is they had a combined up + down expresion col for some plots which was redundant and should be removed. They had also made some heatmaps that didn;t show very much difference between case control, the data probaly needs to be normalized by the genes overall expression, but I need to check prevous work to remeber how to best do that |
| 2022-10-10 | QC approach for hebenula | We went throught boxplots Bukola had made for the data, I suggested she add geom_jitter and how to make that work with geom_repel to help show more details about the data. We also discussed direct vs. standard evaluation of variable and how that makes writing funcitons with tidyverse tricky, but how she can use aes_() to do stadard eval with ggplot |
| 2022-10-05 | How to check technical effects for RNAseq data | I walked through our process for buld data QC, which involves making many exploratory plots of QC metrics and know groups (like batch, or case/control) to understand patterns and identify problematics samples. Then later implementing cutoff values either based on stats (like a 3 MAD cut off) or knowlege of ressonable values. They will spend some time plotting QC values, adapting code from smoking mouse, then we will meet again to interpret these plots. |
| 2022-10-05 | Reviewing GO results and dotplots | We went over the dot plots she made for GO analysis from the multiple DE test she ran. The plots look good, but we identified that they needed to use the default q cutoff to get useful results. She will rerun the GO analysis and replot the results. |
| 2022-09-30 | Working on making a violin plot for just one gene. So by brain region rather than gene type | We adapted my_plotExpression() (a function I wrote) to work for Bukola's data. This required some debugging as subsetting to just the one gene in question altered how some internal dataframes looked. I also gave Bukola some pointers about saving plots using ggplot. |
| 2022-09-30 | Question on the feasibility of some approach with HALO (for the AD project) | Sang Ho walked me through an analysis they want to do for the AD project, it involves annotating HALO data. We talked thought a strategy, this may be a bit computationally tricky to implement but it seems doable. |
| 2022-08-22 | DE analysis introduction | I went over the DE pipeline we use, noting that the model development is the most demanding and non-static part. We talked specifics for their dataset which has some experimental design to consider as its organids and is diffrent from patient case control. I posinted Geo to scripts where we do QC, expression cutoff, and my run_DE script |
| 2022-08-18 | Git push help | Heena saw old commits pop up on slacks git notifications when she pushed commits she had locally on her laptop, but they didn't reappear in the git history. I think she did everything right and there might be something strange with the behavior of the slack message (as thats the only place things seemd wrong). We did some detective work between the files and the commits, everything seems good. Heena was able to then pull to the cluster with out conflicts |
| 2022-08-17 | check the models and the results I have obtained so far from the DEA | Had to work over slack again as Daianna was having trouble with zoom. Working with the feedback from the previous meetings, the experimetn has been narrowed down to 5 DE runs, and then comparing some pairs of the outputs. We were unsure if we should include mitoRate as a variable in the adult model as it correlates highly with totalAssignedGene, but decided to include it for now to match the model used in the pup DEA. I also sent her some code I have used to make scatter plots of t-stats to help compare DE results. |
| 2022-08-10 | Check the model design of the smoking mouse project | We intended to meet on zoom, but Daianna's connection was bad so we used Slack to chat. Daianna has made many plots and visuals about the many DE analysis for smoking mouse. I gave her some feedback about orgaizing her slides so the figures can practically be used inform DE models, right now everything is a bit scattered as shes planning on running 7 analysis so there is a lot to consider. We will need to meet again to finish this. |
| 2022-08-03 | Review results of Varaince Parition for smoking mouse | Daianna showed me her varianceParition plots, and we talked bout how to design the DE anlaysis based on what she's oberved in the mouse data. I advised to keep things simpler (ie not create too many groups) but rather use models to control for vaiables adding variance. We will meet next to talk model design for this work. |
| 2022-07-15 | QC update for smoking mouse | Daianna shared her updated QC plots, adn the one sample she planned to drop based on fastCellQC. I advised that she dig deeper in to how that QC finstion works, and what the cutoff values are, as well as exmaming mito vs. ribo precentages, and a two samples that don't seem to group with others of the same phenotype / |
| 2022-07-07 | help row annotation colors of a pheatmap | I explained how to get pheatmap to use the same color scheme for column and row annotations by making the annotaion tables have the same colname, and suppying a color pallet |
| 2022-07-07 | Subsetting eQTL results with in risk loci | We discussed a strategy to subset the 102 loci in question, and adapted code to subset the FDR signif pairs to work with the location info. |
| 2022-07-05 | QC update for smoking mouse | Daianna shared the updates she made to the QC plots based on our previous discussion, specifically separating brain and blood samples. |
| 2022-06-28 | Review progress on smoking mouse DE project | Daianna walked me through her progress in the DE analysis. We went over QC plots and discussed experimental design. She will check in with Kristen about how to organize the brain vs. blood samples. Currently she dropped the blood sampeles as they looked very different in several QC metrics. But I advised that they just be handled seperatly as it makes senese they look different as they are different tissue, and the signal is probaly biological rather than technical |
| 2022-06-17 | JHPCE Github setup | We fixed Sanjana's ssh set up and got the qrsh command working. We got git configurated for her locally and on JHPCE, as well as set up tokens. Created a test repo, and made commits from her laptop and JHPCE as an example |
| 2022-06-15 | Github setup | We went over github basics and motivation behind version control. Quickly discovered that Sanjana's qrsh command is not working, requiring a password. Ended up using the session to troubleshoot that, with no success :( planning on circling back/re-setting up ssh for her. Will meet later about git setup |
| 2022-06-15 | Revisited the sc analysis and could use some help | We checked Sreya's code against the OSCA DE example run. She was worried that there weren't may significant genes, but her results seemed to be in the same range (10s of genes) as the example. We discussed how maybe there were QC or demographic variables that could have been added to the model, but the data she has doesn't have much to work with. We will revisit when I have maybe done more work with sn DE analysis. |
| 2022-06-03 | I might need a review of how to go about selecting marker genes for the spatialDLPFC data. Also, I'm curious what code you have for making heatmaps showing marker gene expression across cell types. | I pointed Nick to a few scripts used in marker finding for the Tran Maynard dataset, using a few functions from DeconvoBuddies. For marker heat maps we went over how I hace built annotation tables, and a few tricks for optimizing pheatmaps for maker plots. |
| 2022-06-02 | Single cell rna seq analysis | We converted a downloaded dataset from tsv files to a sce object. Went over a strategy for performing DE on single cell data, using OSCA as a reference |
| 2022-06-01 | I have a mouse single-cell RNAseq data that I am aiming to identify cell types in different clusters. | We spent the session getting Sanjana set up better to work on JHPCE, setting up ssh keys, cyberduck, RStudio, and config files. Plan to meet again to set up git + start single cell work |
| 2022-05-18 | Color bar for heatmap | We both leaned how to use the image function to create a annotation bar for heatmaps based on a custom color pallet |
| 2022-05-09 | Cross Reference help | We went over how to create a new type of refrence (Supp Table/Supp Figure). Also walked though the full process of creating a label and then refrencing it in from the text + considreations for formatting |
| 2022-05-05 | Need some help to make a plot | We went thourgh some plotting code Sreya had adapted to make a manhattan plot, and went over which aestetics to change to get the desired plot |
| 2022-04-27 | Help with purrr loops for WGCNA funtions | I helped come up with a stratagedy to loop over 100+ files for an analysis and exreact a portion of the results in to one R object |
| 2022-04-07 | writing papers in google docs and setting up links for figures | We installed and configured Cross Refrence, then went over how to use the lable vs. refrence links + pro tips on how to avoid errors |
| 2022-04-06 | I'd like to consult with Louise about how to make a spatial plot in R using a data set from the HALO FISH-IF module. | We want over some plotting basics with ggplot2, and how to use geom_rect to recreate some spatial plots that a halo module produces in R. |
| 2022-03-24 | Advice on how to increase code coverate with testthat | We applied some test I used for the TREG package to help test more parts of the functions, like checking for errors w/ bad input, warning messages, and qualities of outputs. We discussed possible ways to use testthat on a ggplot, but that might need more thought. |
| 2022-03-15 | TODO | TODO |
| 2022-03-04 | Understand the covariates used in scRNA-seq cell type analysis for a project we are doing with striatal organoids | We went over the files (data and script) for the deconvolution analysis done for the habenula in BSPIII. We also discussed the theroy/methodology for deconvolution. |
| 2022-02-24 | Help building for loops to analyze WGCNA ouput data | We discussed how to build and save data with a for loop and with purrr::map. Went over how to define a function in map to do nested loops |
| 2022-02-24 | I would like to learn how you ran tensorQTL on the MDD data, maybe with using the GPU nodes for it. | Geo was interested int eh workflow I developed for tensorQTL. I went over the requirements and input formats that tensorqtl requirers, and how I had previously made them from our dataset. Also discussed the differnces between the functions and their outputs. |
| 2022-02-15 | Access to the gene info in the rowData of the Summarized Experiment objects to annotate eqtl results | We went over how to acess the rowData, and what the rowData inthe MDD project contains. Ended up adding columns to the eqtl risk snp subsets to help with analysis |
| 2022-01-20 | Troubleshooting ExprssionSet conversion | Fixed row names to both be ensembl IDs, discussed simplifing cell types in sce, converting sce arrarys to matrix |
| 2022-01-19 | Help using BisqueRNA, getting snRNA-seq into correct input format, chosing refrence vs. marker based deconvolution | I shared some detials of our deconvolution approach, we walked through the SCE to Expression set converson, and discussed some issues that may come up |
| 2021-11-03 | Debugging help with rse_tx object | We discussed how to check for duplicate rownames, and stratedgies for variable naming + working with rse objects |
| 2021-10-29 | qc general scripts, rnaseq scripts general, ggplot histogram with breaks | We found a R function that helped produce the plot she was looking for |
| 2021-10-25 | We would love an opinion on our (now cell-type assigned) single nuclei rna-seq data, i.e. how they look - if anything is off, advice for improvement... | Two main issues were discussed: **1**. After batch correction there is one sample that clusters mostly independently from the other samples. This sample did not stand out in QC (althogh this will be re-examined). There is some evidence that this donor might have been clinacally different from the other donors, and since the batch correction worked well for the other samples, there is the possibility that this is real biologal signal. However since there is only one such sample it would be really hard to confirm this, and the inclusion of this sample would counfound the biologcal question of interest. I advisied to drop this sample post-clustering on the grounds that this donor might be too differnt from the others. **2**. Prelimnary results from DEG by cell type for the three groups find mitocondral genes are the most differntly expressed. They are concerned as MT RNA could be a technical artifact (contamination) this tech isn't the best to explore this. But there is are other findings that cellular metabolism may play a role in this condition. I advisied to keep the DEG results with the MT, add the caveat in the paper that this might not be a perfect experiment for this but it could support real differnces in the cells (plus they already have pretty strict MT QC). Also run a second DEA w/o MT genes to see what other signal exists. |
| 2021-10-23 | I am trying to compute DEGs from thefunction registration_stats_enrichment... 
Error in limma::makeContrasts(contrasts = z, levels = registration_model) :
The levels must by syntactically valid names in R | The error came from the names of the clusters just being integers, the names for limma need to be sytactically valid (not just numbers, no spaces, no special characters - basically need to be variable names in R). I advised to simply add a prefix like we did in spatialDLPFC (sp9k1) or even simpler like "c" to her cluster names. Maybe we should add a warning to the function about cluster names since this error is pretty hard for users to de-bug and people often have non-sytactucally valid cluster names (especally with cell type names) |
| 2021-08-26 | using map to cbind a list of six to its corresponding list of lists. The second is a list of 6, each a list of 3. | Did some troubleshooting on nested map functions, when to use ~.x and when to use function() syntax |
| 2021-08-23 | Using purrr and map to loop over datasets and apply qsva | Went over basic, complex, and nested map() usage and how to apply it to Josh's current work |
| 2021-08-20 | Help with JHPCE login issues | We were able to update the keys for the cluster, but the ssh key login was still broken |
| 2021-06-30 | Debugging ggplot code | We reviewed her code and I gave some pointer on what bugs to look out for with certain errors in ggplot |
| 2021-06-17 | Manhattan plot making and tstatistic | Pointed her to some oacjages for creating TWAS plots whe was interested in and we walked through some code I used to compare T-stats from different DE models |
| 2021-06-03 | questions about expression_cut and pca plots | We walked tought script from getRPKM to expression cut to filter rse objects, I also pointed Brenda towards some reasources to get started with ggplot |
| 2021-05-28 | Differential Expression help (continuation of 5/20) | NA |
| 2021-05-20 | Making plots for DE studies | We reviewed the model that Sreya was evaluating for DE. As we as troublshooting the plot functions from the SPEAQeasy bootcamp code. I also advised taht she could create a volcano plot for her results. |
| 2021-05-12 | Making plots for DE studies | We went over some plots we have made for DE previously, (quality control & PC scatter plots, t-stat scatter between models, venn diagrams, and boxplots). Talked about some things to watch out for in her data (small samples size). We are planning to meet again when her data is ready. |
| 2021-04-19 | JHPCE set up on mac | We got ssh key login working, added config files to JHPCE, went though a "hello world" example of using files on JHPCE on RStudio |
| 2021-04-15 | JHPCE set up on mac | Henry needed to reset his JHPCE password as he had forgotten it, but we went through RStudio set up and got cyberduck installed, we will set up a meeting next week for ssh keys and configuration |
| 2021-03-26 | Need help understanding the sce - single cell object | Went over basic functions of SummarizedExperiment and SingleCellExperiment, what a Sparse matrix is - how to convert to non-sparse. Steps to take to use getRPKM on SingeCellExperient. |
| 2021-03-19 | Change point size in vis_clust_grid | We walked througth the SpatialLIBD code to find where the argument has to be changed |
| 2021-03-05 | Maker finding for cell types in single cell data | I showed them the tools I developed in DeconvoBuddies package, and provided links to example code where I had applied these funcitons in previous work |
| 2021-02-09 | Visualizing RPKM valus for genes in Humna and Primarte data | We spent time doing basic Rstudio setup and troubleshooting, and got the data downloaded |
| 2021-02-04 | Github ssh key set up | We got the ssh keys working for Brenda's github |
| 2021-02-04 | Work on habenula deconvolution and debug the deconvolution package | We went over applying DeconvoBuddies functions to hebenula data |
| 2021-01-27 | group_by bug for get_mean_ratio | We are going to try an iterative strategy to keep tables smaller |
| 2020-12-08 | Resolving issues in phenotype data between genotype, expression, and LIBDpheno | Need to resolve swap bugs. Plan to create a table of phenotype data (Dx, age, sex, race) for each BrNum to mach genotype data |
| 2020-12-07 | jhpce set up on mac | Went through the setting up passwordless login for jhpce using ssh keys, and coppied the configuration files from https://gist.github.com/lcolladotor/3b1063db30a206835ee7e086c8f037ee |
| 2020-11-18 | Help clustering sce data | We debugged some code and ultimetly decided that it might be best for Abby to write new code and use the tsne function to cluster and plot the data |
| 2020-11-13 | Using reshape package to transform table for plotting | I recomended using dcast to do a "long" to "wide" data transformation |
| 2020-11-12 | Help adapting ggplot script for TWAS Z-score | We talked about how the data should be structured before using ggplot (transforming some data and adding catagorical columns) |
| 2020-11-05 | LC repo organization | We discussed organizing by analysis (a directory for each one, then prehaps sub- directory for data & plots). Create a readMe for each sub-folder. Use gitignore to keep repo from getting too big. |
| 2020-10-27 | Plotly help if possible? I'm trying to export an html file that allows the user to look at each snp/gene on the plot, and I am almost successful. Leo recommended that I talk to you on this matter. | Needed to use highlight_key and highlight functions to select points between plots. Used rstats example as guide https://gist.github.com/lcolladotor/350ac8843e153d135f64880a1d029b14 |
| 2020-10-21 | Question: Subset center regions of a set of different length sequences | [BioC Support website answer](https://support.bioconductor.org/p/134532/#134925) |
| 2020-10-20 | Help with spatstat | spatstat package https://spatstat.org/releasenotes/spatstat-1.39-0.html, L function https://www.rdocumentation.org/packages/spatstat/versions/1.64-1/topics/Lest, Kmark https://www.rdocumentation.org/packages/spatstat/versions/1.64-1/topics/Kmark |

