# Manisha

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2025-12-05 | variance partition by cell-type | Explained how to use fitExtractVarPartModel() per cell type and set up a shell script for batch execution and later generate summary heatmaps from the model outputs. |
| 2025-12-04 | troubleshoot error implementing dreamlet vignettte | I explained aggregateToPseudoBulk() object formats and where voom belongs in the workflow. clarified that voom is applied after pseudobulking, not re-pseudobulking.
Helped resolve their variance-partition error caused by skipped preprocessing steps. |
| 2025-11-24 | variancePartition plots troubeshooting progress | After implementing the corrections, the variance partition plots became consistent and more informative. We identified the issue as the use of BioBase::ExpressionSet instead of gene expression (logcounts) as input parameter to fitExtractVarPartModel(). |
| 2025-11-24 | code review for EDA plots | I identified inconsistencies in their variance partition workflow and reviewed the code to locate the source. I helped correct the input setup by ensuring consistent pseudobulk data (Seurat to SCE, calculate logcounts, nCells > 10) and proper use of fitExtractVarPartModel(), improving consistency across all plots and analyses. |
| 2025-11-20 | review variancePartition plots | We discussed the variance partition plots. The plots showed maximum variance explained by nCells and less than 10% by other covariates. I suggested exploring PC variance using getVarianceExplained() and getExplanatoryPCs() from scater package to better understand covariate behavior. |
| 2025-11-19 | writing lmer function | I noted the issue in the lmer formula used for variance partitioning and clarified how to correctly specify the response variable. We reviewed initial variance partition plots together and discussed their interpretation. I suggested adding mitochondrial and ribosomal ratios as as additional covariates to improve variance explanation across samples. |
| 2025-11-13 | pseudobulk analysis | I described how I use variancePartition, including example plots from the vignette https://www.bioconductor.org/packages/release/bioc/vignettes/variancePartition/inst/doc/variancePartition.html and CCA plots to assess and select covariates for pseudobulk analysis. I walked through the lmer-style syntax for specifying fixed and random effects. I also explained the purpose of block parameter in voomLmFit() and showed how it is incorporated into the function call. |
| 2025-09-26 | QC steps for sn-RNA seq | Provided a walkthrough of snRNA-seq QC steps, covering droplet filtering (empty drops, doublets), Harmony batch correction. I explained him interpretation of UMAPs, clustering results, and registration heatmaps for better understanding of the analysis results. |
| 2025-09-04 | Understanding jaffelab::cleaningY() | I explained the overall idea of the function, its arguments, and the reasoning behind the models and math. Demonstrated usage with code and plots for cases vs. controls, simple vs. interaction models, and choosing the P argument. |
| 2025-08-19 | Code review | We discussed troubleshooting steps to identify silent errors in code. Durig the review, we noticed she was using raw_data instead of filtered_data which caused the code to run out of memory when attempting to load `raw_feature_bc_matrix` and normalize the data. |
| 2025-08-18 | Steps in snRNA-seq data processing | I explained QC steps, covered DropUtils::emptyDrops() and DropUtils::10readcounts |
| 2025-08-13 | Various training steps | We talked about best practices for adapting code, structure of template project (Github, JHPCE), using git co-author syntax and here::here() |
| 2025-08-12 | JHPCE setup: JHPCE config files, Laptop config: git on laptop, using GitHub to sync laptop & JHPCE | We worked on setting up JHPCE config files, git on laptop, using GitHub to sync her laptop & JHPCE. |
| 2025-08-11 | Laptop config: ssh keys, Cyberduck | We went over laptop configuration including SSH key setup and guided in locating the correct authenticator app to retrieve the verification code. We also configured Cyberduck and showed her how to bookmark file to different project paths in Cyberduck. |
| 2025-05-30 | pseudoBulkDGE optimization | We discussed and brainstormed about writing her pairwise models and identified covariates that were repeated across some models. |
| 2025-05-22 | steps to consider when selecting variables to build an interaction model for DEG analysis. | We discussed pseudobulk analysis steps, focusing on covariate selection strategies for DEG modeling. Helped her identify an issue in her custom pseudobulk analysis function where the covariates argument was incorrectly handled, leading to unexpected results. |
| 2025-03-25 | DE strategies, pseudobulk process and using pseudoBulkDGE() | We discussed the DE analysis steps, focusing on pseudobulking. I explained the overall workflow I am using, including the use of pseudoBulkDGE(), the covariates to consider, and how to set coefficient in the design matrix for analysis. |

