# Nick

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2024-10-01 | PRECAST recommendations | I pointed to https://github.com/LieberInstitute/visiumStitched_brain/blob/devel/code/03_stitching/07_precast_unstitched.R and mentioned that some evidence from stitching analysis (in particular, https://github.com/LieberInstitute/visiumStitched_brain/blob/devel/plots/03_stitching/agreement_at_overlaps.pdf) suggested SVGs were slightly favorable to HVGs as input |
| 2024-09-24 | SpatialExperiment::rotateObject() with stitched data | She encountered an open bug with this function that I described. I noted a workaround was to rotate in increments (e.g. 90 degrees 3 times instead of 270 degress once). |
| 2024-09-20 | Addressing NDA submission errors | I recommended using a GUID-mapping table I generated in the spatialDLPFC dataset, since the issue was related to subject-GUID mapping. |
| 2024-09-09 | Using modules, slurmjobs, and certain partitions | I demonstrated to use of modules for command-line software, R, and python. I pointed to slurmjobs vignettes and the 'job_single()' function in particular. I noted katun or caracol are reserved partitions that can be accessed with '-p katun' when using srun or sbatch. |
| 2024-08-20 | Getting an integer vector from factor of integers | I recommended the code 'as.integer(levels(clusters)[as.integer(clusters)])' to address the particular use case, for a factor of integers 'clusters' |
| 2024-08-16 | pseudobulking with Seurat | She encountered a cryptic error when pseudobulking on particular data. I recommended trying the code with simpler data to identify whether the data or code was a problem. |
| 2024-08-08 | Trimming options with SPEAQeasy | I explained that often samples aren't trimmed by default, as the adapter content metric from FastQC must fail to trigger trimming. I mentioned the '--trim_mode force' option to force trimming |
| 2024-08-06 | Adapting scripts to SLURM and using the 'fusion_twas' module | I described several common sbatch options and their syntax (and SGE equivalent). We ultimately discovered that the 'fusion_twas' module was never rebuilt, so I did that afterward |
| 2024-08-02 | Running nnSVG and visualizing PRECAST results | I found a basic example script where I ran nnSVG and described the array job I use to run it for each sample, followed by an ordinary job to aggregate results by averaging gene ranks |
| 2024-07-26 | NDA- submission and authentication | I showed the specific scripts I used to perform the upload, described the process for resetting your password to obtain one usable for the CLI, and the python library for authenticating with NDA |
| 2024-06-21 | Overview of running PRECAST | I discussed possible choices of input genes, the fact that raw counts are used, and pointed to some example code where I had run PRECAST |
| 2024-06-11 | Overview of using NDA | I reviewed the general process and location of code I used for the spatialDLPFC project for uploading to NDA |
| 2024-06-11 | vis_clus issues | She showed issues with 'vis_clus' when plotting logical variables, which we ultimately determined to be a spatialLIBD bug (she wrote a GH issue as a result) |
| 2024-06-08 | Shiny issue: reading previous manual annotation | I showed the source code inducing the error message (suggesting a mismatch in keys between previous annotation and the current SPE object), and we increasingly tested simpler annotation examples until something worked. Ultimately, we think the editor that was used in manually modifying the annotation CSV may have been the culprit |
| 2024-06-03 | Scripts for log normalization and GLM-PCA | I pointed to an initial version of my code which had a simpler workflow than the reference code she was modeling hers after, and gave a brief explanation of the purpose of GLM-PCA |
| 2024-05-30 | Getting SPEAQeasy started | I helped with building the samples.manifest file and addressed a permissions issue on annotation files that was halting the first SPEAQeasy run |
| 2024-05-14 | Log normalizing counts in spatial data | I showed the code I've used for log normalizing spatial data counts, and linked to OSCA's section on log normalization via deconvolution, after which the code was based |
| 2024-05-14 | Resolving merge conflicts | I showed the syntax git uses when a merge conflict occurs, and how to resolve conflicted files |
| 2024-05-08 | Understanding misalignment in Visium stitching | She showed that capture area positions from images stitched with ImageJ disagreed with those stitched in the python-and-Samui-based workflow. I went through suspicious areas of code without success. Later, she identified that it was an issue related to differences in scalefactors and image resolutions, and differences in underlying assumptions between the stitching steps |
| 2024-05-01 | Deploying and testing Shiny app locally | I went through the scripts involved in locally deploying a Shiny app, as well as which files to download from JHPCE to interactively test |
| 2024-04-26 | Module-related JHPCE files | He noted that an ldpaths and Makeconf file were created with bad permissions sometimes when working with the r_nac module at JHPCE. We identified that switching from one conda-based module to r_nac triggered the issue, and I suggested tricks for changing permissions on the files to prevent the issue from recurring |
| 2024-04-23 | Running nextflow based pipeline with singularity | I found a config file for the particular software that supported singularity, and noted which module to use at JHPCE (also warning that it may require a good amount of memory on the first run) |
| 2024-04-19 | Resolving merge conflicts | I outlined that staged but not committed changes prevent merging, and how to resolve merge conflicts in files modified in different ways from two different sources |
| 2024-04-15 | Understanding SPEAQeasy and using correct annotation | I outlined the process of running SPEAQeasy as a whole, and showed how to find which annotation settings were used on a particular project |
| 2024-04-10 | Running SPEAQeasy with conda | I suggested some temporary workarounds to get SPEAQeasy to recognize a conda environment with the necessary dependencies, but noted that we didn't officially support using conda for this purpose |
| 2024-03-20 | More troubleshooting misaligned image | We interactively ran the python code for reading in ImageJ transforms to rule out an issue where the wrong data was read in. Ultimately, we couldn't find issues with the data, but the Samui full-res images still seemed misaligned relative to the low-res images |
| 2024-03-19 | Troubleshooting misaligned image in Samui | I pointed to suspicious areas of code where dataset-specific regexs were originally used, though the regexs looked good for his data as well. We decided to interactively walk line by line at a later date |
| 2024-03-15 | Plotting to a multi-page PDF with 3 plots per page | I suggested building a list() where each element was a 3-piece plot (combined with a function like cowplot::plot_grid), then using print(plot_list) |
| 2024-03-13 | Installing cellprofiler at JHPCE | I suggested using conda after pip failed (missing system dependencies). Ultimately, my troubleshooting was enough to just build a module for everyone |
| 2024-03-07 | Adding notes to Samui | I described how a markdown of notes could be added using the Samui python API, though this is not how I had done it in a previous project ( I was unable to trace the original method I used) |
| 2024-03-05 | Better algorithm for dealing with overlapping images in Samui | I helped implement an algorithm taking the minimum pixel intensity in case of overlapping images to display an H&E image in Samui |
| 2024-03-04 | Setting up SSH keypair for passwordless login to JHPCE | I diagnosed several potential issues, ultimately missing one detail that was the culprit: permissions were too open on some .ssh files on her laptop |
| 2024-02-16 | Adding phenotype data to coldata | I described my typical strategy of using left_join by sample ID, as well as ensuring rownames don't get lost from conversion to a tibble (thus dropping colnames from the SummarizedExperiment unintentionally) |
| 2024-02-12 | Adding packages to a custom R module | I noted that the r_nac module was built similarly to conda_R, where the user doesn't have to do anything special to install more packages. We ultimately traced the issue to permissions problems on files created as part of the proper use of the module by other users, likely due to problematic 'umask' settings |
| 2024-02-05 | Follow-up: removing large files from version control | I ultimately recommended 'git reset --soft' to the commit ID before the recent mistaken addition of the large files |
| 2024-02-02 | Troubleshooting GitHub authentication issues | I advised using the SSH address (not HTTPS) for the 'git remote', ensuring the 'git config' email matches the primary GitHub email, and using the up-to-date SSH key (not RSA, which is no longer supported/ recommended) |
| 2024-02-01 | Removing large files from version control | We explored options: BFG cleaner, git rebase and git reset --soft and discussed which was best for her situation |
| 2024-01-30 | Working with SLURM | I described the use of 'srun' (including with X11) vs. 'sbatch', and generally recommended 'sbatch' where possible to document how analyses were run/ ensure reproducibility |
| 2024-01-26 | Running python on cluster | I mostly focused on my setup using VS code with its remote SSH extension, and custom keyboard shortcuts for running python code interactively |
| 2024-01-26 | Creating a module | I mostly confirmed the general process he had started for a particular module made from software packages as a precompiled binary |
| 2024-01-24 | Follow up on stitching for Samui | I described how code might change when using IF images rather than H&E, for which the code was originally developed |
| 2024-01-08 | Creating stitched image in Samui from ImageJ estimates | I described how to adapt a script I wrote for NAc to her dataset, where the goal was simply to display a stitched-together image in Samui |
| 2024-01-05 | Investigating visual problems in Samui image | I traced the issue to the use of 8-bit integers, where an overflow occured during normal addition of pixel values (the solution was to use floats while computing the mean, and then convert back to uint8) |
| 2023-12-12 | Help adding phenotype info to colData | I described how I typically use dplyr::left_join, as well as how to add back missing rownames to the colData (or colnames of the SummarizedExperiment) |
| 2023-12-11 | Investigating R package installation conflicts | I described the conflict between SGE and SLURM R packages, as well as identified lock files preventing re-installation of problematic packages |
| 2023-12-08 | Investigating error in qSVA funtion call | We traced the offending line of R code in the qsvar package and I described how unit testing could identify problematic function arguments and give more informative error messages |
| 2023-12-08 | Performing 'jaffelab::s' on large tibble efficiently | I noted that the function could be applied before the data was converted to long format, where it was impractically large to work with |
| 2023-12-08 | Follow up on stitching for Samui | We identified issues causing incorrect coloring in the Samui outputs |
| 2023-12-05 | Creating stitched image in Samui from ImageJ estimates | I described how to adapt a script I wrote for NAc to his dataset, where the goal was simply to display a stitched-together image in Samui |
| 2023-11-21 | Overview of image stitching process | I described the workflow for stitching Visium capture areas with Samui, and various Samui API functions like 'add_chunked_feature' that are helpful |
| 2023-11-08 | Modifying a global-scope variable inside a function | I showed a workaround for making sure a variable has global scope before editing it inside a function, though I noted it's better not to use a function in her particular case |
| 2023-11-01 | Issues linking repo to github | I identified two separate issues: the repository name and using HTTPS remote instead of SSH |
| 2023-10-30 | Interpreting decision tree and spot-deconvo plots | I walked through how a decision tree works and can be interpreted, then described how correlation and RMSE are computed in a couple spatialDLPFC spot deconvo plots |
| 2023-10-30 | Issues with tensorqtl module | He noted that the wrong version of python was being used, and we eventually traced this to user-specific conda settings interfering with the module |
| 2023-10-25 | Interpretation of "replication" plots and performance of QSVA models | We interpreted the intuitive meaning of a formula from some old code, which attempted to quantify the similarity of a set of significant genes between datasets. I also helped interpret the meaning of a plot based on this metric |
| 2023-10-24 | Example datasets and getting started with data science | I recommended 'spatialLIBD::fetch_data' for easy retrieval of public data to get started with spatial computational analysis. I also recommended pushing for an account at JHPCE, where computational resources are more plentiful, and getting used to submitting jobs, accessing software, etc is valuable to learn |
| 2023-10-17 | Nextflow issue when running SPEAQeasy | I noted that conda_R seemed to be changing the version of java loaded, which affected how the nextflow module worked. I recommended unloading conda_R and avoiding the loading of conda_R via the .bashrc |
| 2023-10-16 | Setting up and running SPEAQeasy on a new cluster | I described the general process of setting up SPEAQeasy and gave recommendations for his cluster: using singularity and SLURM-based installation/ set-up |
| 2023-10-13 | Installing SPEAQeasy and setting up main script | I mostly covered documentation but also the appropriate options for his particular data |
| 2023-10-13 | Troubleshooting a SPEAQeasy error | I investigated a "failure to submit process to scheduler" error using 'sacct' and similar commands, ultimately discovering the issue was related to SLURM configuration. There was an email chain with bithelp to follow up |
| 2023-10-11 | sbatch issue with SPEAQeasy | I followed up with bitsupport, as the issue seemed to involve some failed DNS query internal to SLURM, rather than SPEAQeasy |
| 2023-10-11 | Interpreting and refactoring "concordance" formulas in QSVA results | We walked through old code which aimed to quantify the similarity between significant DE results, interpreting formulas from the code and constructing more intuitive formulas |
| 2023-10-04 | Refactoring QSVA code | I gave general advice on re-writing code-- keeping separate scripts, chunking code into segments and testing equality of outputs between old and new code after each chunk, and other strategies |
| 2023-09-28 | Dropping extra factor levels | I described the 'droplevels()' function, designed to remove unused factor levels |
| 2023-09-27 | Confidence metric in spot deconvo model | I discussed how we selected training data for the spot-deconvolution image model-- using logistic regression to compute a confidence metric across the original training examples, that we then binned into 4 quartiles to re-select new examples to label in a less biased way |
| 2023-09-26 | Array jobs over variables with SLURM | I mentioned slurmjobs::job_loop and also described how to use it in conjunction with getopt in R for looping over several variables |
| 2023-09-25 | SGE vs. SLURM R package conflicts | She had an issue installing a particular R package, which we pinpointed to which modules were loaded (including via bashrc). I also described the general problem of SLURM and SGE versions of JHPCE sharing a library path, which could result in subtle problems. I recommended deleting SGE packages (better would've been backing up!) and reinstalling on SLURM |
| 2023-09-19 | Customizing the home page for spatialLIBD apps | I noted the 'www' directory (or the directory passed to the 'docs_path' parameter) controls the home page, and we typically use a relative soft link to the main repository README for the bulk of the content. |
| 2023-09-19 | Overview of the stitching process for split Visium samples | I described the general workflow, involving ImageJ, Samui, VisiumStitcher, and custom R + python code needed to eventually produce SpatialExperiment objetcs with one donor per sample. I focused on the high level of what the Samui piece looked like/ how much work is involved |
| 2023-09-12 | SLURM array jobs and X11 | I showed code examples of writing array jobs with SLURM (and how it compares to SGE), then diagnosed an X11 forwarding issue where the '-x11' srun option was insufficient. Adding X11-related configuration in the SSH config fixed the issue (i.e. ForwardX11 and ForwardX11Trusted lines) |
| 2023-08-28 | Creating documentation sites with bookdown | I described the pieces that go into a bookdown-powered documentation site, showing RMD code examples and the GHA workflow that deploys the site |
| 2023-08-23 | Displaying info about cells, not spots in Samui | I noted that Samui supports many types of features, and the spatial coordinates of cells can be supplied instead of spot coordinates to display features related to cells |
| 2023-08-22 | Interpreting spot deconvolution results | I described the meaning of cell2location outputs and how to compare outputs between software tools. I also described where plots came from in R |
| 2023-08-17 | Missing genes in Samui | He noted that not all measured genes were displayed in the Visium_SPG_AD project. I found in the code why I subsetted and made a GH issue to fix it |
| 2023-08-16 | My coding set up | I shared my favored set up for getting computational work done: working directly on JHPCE via the SSH extension for VSCode, using system-wide JHPCE modules for consistent software versioning, and X11 for interactive plotting (with a note I tend to just create and view PDFs for complex plots) |
| 2023-08-16 | Recommendations for learning more data science skills | My major recommendation was learning version control with git, though I also mentioned learning SGE/SLURM also is a valuable skill for larger-scale coding projects. I helped him create a git repository for his current project (including account set up) and described the basics of git add, commit, and push |
| 2023-08-14 | Misc spot deconvolution questions | I described how the various scripts connect in spatialDLPFC for my work with deconvolution, to help share and re-use them for her project |
| 2023-08-11 | recount 3 permissions | I explained the status of the recount-pump transfer, where files were, and noted that chris or JHPCE admins would have to change permissions to allow her access to some files |
| 2023-08-11 | Using modules at SLURM and configuring bashrc | I noted that modules at SGE vs. SLURM are totally disjoint, and that the HOSTNAME trick originally used in the team recommended bashrc didn't (at the time, though this has recently changed) work anymore, and the SLURMD_NODENAME variable can instead be used to infer where the user is |
| 2023-08-09 | Using Samui from start to finish | I did a complete tutorial of using the Samui API to create Samui-importable directories, including how to preprocess image files and how to host results publicly |
| 2023-08-07 | Normalizing spot deconvolution results to answer biological questions of interest | He noted that just taking the most plentiful cell type in any cluster was leading to too many clusters with excitatory layer-5 cells. I mentioned that the raw outputs of spot deconvolution tools are fairly unreliable, but they still carry useful information when normalized. For his example, I mentioned dividing by the total number of cells for each cell type when making comparisons between cell types |
| 2023-07-27 | Quantifying spatial promiscuity of genes across clusters | I mentioned (information) entropy as a metric that would determine how well a gene is confined to a particular cluster (using average counts of a gene across all spots in each cluster, then normalizing the sum to add to 1), but cautioned that I wasn't familiar with favored metrics within the field |
| 2023-07-25 | Troubleshooting GHA workflow errors when building workshop | I helped discover the source and solutions to errors and warnings (mostly from BiocCheck and R CMD check), and found how to specify a single author in in-text citations |
| 2023-07-19 | Spot deconvolution workflow overview | I pointed her to spot deconvolution scripts used in spatialDLPFC and the high-level overview of the workflow, as well as how we trained the decision tree classifier |
| 2023-07-18 | Loading large files in R | I noted that he ran out of memory in his JHPCE job, which crashed R, so I suggested increasing 'mem_free' and 'h_vmem' |
| 2023-07-17 | Sharing conda environment | I referred to examples of JHPCE modules I've created that activate shared conda environments, and explained the key commands used to get a similar module working |
| 2023-07-12 | Performing QSVA with genes or with different annotation | I recommended finding and trying to generalize the process a previous coworker followed to produce the list of degradation-associated transcripts, to limit relying on exact transcripts with an exact GENCODE version. I noted that you can convert transcript data to genes (albeit with lost information), but not vice-versa, so in theory either transcript or gene-level data could be supported by converting to genes |
| 2023-06-09 | Displaying spot coordinates in Samui | I described the 'add_coords' function, how features link to existing coordinates, and that coords must have at least one associated feature to display |
| 2023-06-08 | Using the Samui API to display data locally | I referred her to recent versions of my code (spatialDLPFC and SPG_AD projects) and walked through the high-level steps of each |
| 2023-06-07 | Troubleshooting SPEAQeasy error | I showed that the error was essentially a failure to allocate memory and recommended doubling required memory for the failing SPEAQeasy process until success |
| 2023-06-02 | Ignoring a directory with gitignore | I described that an entire directory (rather than all of its contents) can be ignored, and should be specified relative to the directory containing the .gitignore |
| 2023-06-02 | Debugging rewritten code | We looked at some old code vs. an adapted version, which was not producing the same output. I recommended splitting the code into ordered sections, and executing the old and new version of each to identify exactly where the error was occurring |
| 2023-06-01 | Troubleshooting unexpected SPEAQeasy output | I discovered she was using the --small_test argument and not --input, so only the small 3-sample test set was running instead of her actual data |
| 2023-05-26 | Interpreting spot-deconvolution plots | I walked through the meaning of certain information-dense plots I made to show spot-deconvolution results |
| 2023-05-25 | Subsetting RSE by chromosome | I recommended filtering rows of the RSE via 'seqnames', which would return genes (or features in general) of the particular chromosomes needed |
| 2023-05-25 | SPEAQeasy defaults | She asked about any quality-check-related options SPEAQeasy had (I pointed her to '--ercc' for applicable data) and whether trimming defaults were reasonable for her data |
| 2023-05-24 | Using Samui's API to visualize spatial data | I described the general workflow needed to start from raw images and spaceranger outputs, and end up with a Samui-compatible directory that can be dragged into the browser (locally) to view Visium data (including segmented fluorescence channels) |
| 2023-05-18 | Creating many configuration files differing by one variable | I suggested creating a template configuration file, then looping through her data, using the sed command to write configuration files with the relevant variable replaced from the template |
| 2023-05-18 | Merging two dataframes | She wanted to add the columns associated with unique rows in one data frame to the other, so I suggested combining the 'unique()' command with 'left_join()' |
| 2023-05-17 | Renaming many files by a pattern | I suggested using regular expressions in R to get the new filename from a given old filename, then file.copy to perform a safe test, and finally deleting the old files |
| 2023-05-16 | Help with SSH keys with GitHub | She was unable to push to GitHub on her laptop. It appeared she didn't have an SSH keypair set up with GitHub, so we set that up to fix the issue |
| 2023-05-02 | Interpreting SPEAQeasy metrics | I described typical expected alignment rates, the difference between concordant and overall map rate, and details about other SPEAQeasy output metrics |
| 2023-04-25 | Creating a blog post on the rstats website | I explained that at the time, I just created the RMD file and added any referenced images to the rstatsclubsource repo, following naming conventions that include the post date and hyphens between words in the blog title. I believe Leo did some manual work to get it fully published, so I referred to the full guide in case my method was incomplete: http://research.libd.org/rstatsclub/2018/03/09/contributing-to-the-libd-rstats-club/ |
| 2023-04-21 | Ensembl IDs vs. gene symbols with cell2location | I explained how cell2location is agnostic to what gene identifiers are used, but that gene indentifier type must match between spatial and reference single-cell data. I mentioned the org.Hs.eg.db package. |
| 2023-04-19 | Modules and reproducible software set-up for python | I described when I make a module for python-based tools, the benefits of conda vs. python virtual environments, and related topics |
| 2023-04-17 | Properly tracking git contributions | I suspected improper configuration of email associated with her git commits, which was indeed the problem. Her commits moving forward are associated with her GitHub account, but we couldn't figure out how to retroactively regain credit for commits done with the wrong email |
| 2023-04-14 | When and how to merge git branches | I described 'git pull' to merge in remote changes, and using the 'vi' editor to write a merge message |
| 2023-04-10 | Information needed for Samui | I explained which paths I'd need to get Samui running on our data, and we discussed which features might be useful to show |
| 2023-04-07 | Properly transferring from dcl01 to dcs05,dcs04 | I described how ACLs are properly set up at dcs05 to inherit downward automatically, so just an 'rsync'/ move to trash is necessary in those transfers |
| 2023-04-06 | Git-LFS error messages | I explained the purpose of Git-LFS, that it's configured for certain repositories, and that we can load a module to use it |
| 2023-04-04 | Configuring X11 for plotting at JHPCE | I described my use of XQuartz, the 'xhost +local:' command, and the proper ordering of these tools in combination with SSHing to allow plotting to work |
| 2023-03-28 | Creating modules at JHPCE | I described what we use modules for, the general approach to making them for common software types (binaries, python packages), and walked through the process by making a new FastQC module |
| 2023-03-22 | Using git and RStudio to work with R Markdown files | I helped him set up git on his laptop (username + email, SSH key), showed how to edit R Markdown files using RStudio, and basic version control (git add, commit, and push). |
| 2023-03-22 | SPEAQeasy error | The error message was cryptic, but made more clear in the latest SPEAQeasy: the transcripts FASTA mismatched with the GTF (custom annotation was used) due to a typo in the gene ID in the GTF. |
| 2023-03-15 | Quantifying a single gene not in SPEAQeasy's default reference | I initially mistakenly suggested kallisto, but later clarified that using featureCounts with a custom single-gene GTF from the BAM files (produced by SPEAQeasy) would be the proper way to quickly quantify a single gene |
| 2023-03-08 | Finalizing genotyping + expression script | We discussed how to merge two datasets in R, making sure they shared the exact set of genes |
| 2023-03-01 | Version controlling renamed directories | I described the need to 'git add' both the old filenames and new filenames, and the use of 'git add --all' to reference deleted files. |
| 2023-03-01 | Miscellaneous R questions | I recommended code for matching two data frames up by common genes, and explained that matrices don't support multiple data types (instead a 'data.frame' might be used) |
| 2023-02-15 | Using a gitignore to not version control specific files | I showed how glob expressions can be used to conveniently match many files across potentially several files, and described gitignore-specific rules, such as certain wildcard expression matching files no matter what directory they are in |
| 2023-02-06 | Adding figures to OneDrive and google docs with CrossReference | I went over details like naming the OneDrive folder and correctly using CrossReference to refer to that name in figures and references to those figures |
| 2023-02-03 | Organizing figure components for Illustrator | I helped port several plots into Illustrator as a figure, describing our normal process of using PDFs and linked files to maintain resolution. |
| 2023-02-01 | Lining up gene expression and genotyping data | I showed how to filter for individuals with a certain condition, and subset two data frames with the same criteria. |
| 2023-01-25 | Setting up GitHub SSH keys | She was unable to clone private repositories due to a problem with her SSH key with GitHub. We solved the problem by setting up a new key pair using the recommended Ed25519 algorithm instead of the deprecated RSA algorithm. |
| 2023-01-25 | Managing software dependencies with Nextflow | We focused mostly on the options Nextflow provides for managing software dependencies: Lmod modules, conda environments, and docker + singularity containers and the benefits of each potential approach |
| 2023-01-20 | SPEAQeasy error | We identifed that SPEAQeasy cannot handle runs with only one sample, but that the intention was to use multiple samples (the manifest did not use unique sample names) |
| 2023-01-18 | Integrating R scripts with Nextflow | We went over several concepts in Nextflow (e.g. processes and channels) and discussed how to invoke R scripts inside processes. |
| 2023-01-10 | Help identify the source of unexpected NA values | We uncovered the source of some unwanted NA values in some genotyping data and eliminated it by removing some code |
| 2023-01-03 | Adapting spot-deconvolution code to new data | We talked about how to compute KL divergence between 2 groups of cell-type proportions on her data using a variation of my code |
| 2022-12-06 | resolving a merge conflict | I described the manual process for resolving a merge conflict with git when git cannot automatically merge two branches |
| 2022-12-05 | Identifying the source of an error | We pinpointed an error message as being due to trying to find the 'colData' of a list containing Summarized Experiments rather than calling 'colData' on the SummarizedExperiment itself |
| 2022-12-01 | coloring plots by a continuous variable | I described how to color ggplot2 plots by a continuous variable, adjust the palette, and other ggplot-related syntax/tricks |
| 2022-11-30 | wrangling and reformatting expression data | I recommended some data-preprocessing steps for later downstream manipulation of the data |
| 2022-11-23 | preprocessing and reformatting genotype and expression data | I gave general advice for how to preprocess some data, including changing data types, transposing matrices, and dropping columns to format things for a collaborator |
| 2022-11-16 | organizing plots and output files | I described 'facet_wrap' and showed that for some situations, 'plot_grid' with a single output PDF (with width and height scaled appropriately) does well |
| 2022-11-15 | understanding linear mixed-effects models | We generally discussed linear mixed effects models and some common terms used as fixed effects in genomic data |
| 2022-10-28 | formatting genotype data into a matrix for each gene | I described how to transpose matrices, change their type, drop columns, and related tricks to solve a data-formatting problem asked by a collaborator |
| 2022-10-13 | Lifting results between hg19 and hg38 | I mentioned rtracklayer::liftOver and showed a code example of lifting over genomic coordinates for a SummarizedExperiment |
| 2022-09-26 | Setting up SSH keys between login and compute nodes | I described the need for SSH keys between the login and compute nodes at JHPCE, and how an incorrect set-up will manifest as a prompt for your password when using 'qrsh'. I referenced https://jhpce.jhu.edu/knowledge-base/authentication/ssh-key-setup/ |
| 2022-09-23 | Setting up SSH keys for JHPCE | We debugged her SSH set-up with JHCPE, finding a syntax mistake, confirming the contents of the '.ssh/config' file, and other details to ultimately get the traditional RStudio + JHPCE set-up working smoothly. We touched a bit on the process for using git from JHPCE but didn't finish fully setting things up |
| 2022-09-16 | Interaction between .bashrc and 'module load' in 'qsub'd scripts | I described how 'module load conda_R' lines in a submitted shell script override the default version of R that can be loaded by default using the '.bashrc'. In this case this undesired interaction caused a corrupted R package to load and return an error |
| 2022-09-16 | Modifying a shell script to segment a VCF by genomic region | We adapted someone else's code, slightly changing some awk commands to use cut (which I'm more familiar with) and using a for loop rather than piping a file to a while loop. This allowed the code to work as intended on the data |
| 2022-09-12 | Setting up SPEAQeasy at JHPCE | I pointed to installation guidelines for the cluster to resolve issues about R packages not being installed and a problematic nextflow version. |
| 2022-08-24 | Use of git from multiple local locations | I described how to smoothly 'git pull' when updates have been made to both the local and remote repo (adding + committing local changes, running 'git pull', and handling a smooth merge) |
| 2022-08-22 | Moving and correctly accessing HDF5-backed SummarizedExperiments | I described proper saving and loading of SummarizedExperiment derivatives whose assays are HDF5-backed using the HDF5Array package, and how to convert between HDF5-backed objects and "ordinary" in-memory objects |
| 2022-07-18 | CUDA issues with cellpose module | We worked through a few issues in the cellpose module, which each had a different cause. In one case, the version of torch/CUDA was outdated for the hardware. In another case, user-specific libraries were being referenced instead of the central module's libraries. |
| 2022-07-13 | Addressing SPEAQeasy error messages | The error messages involved a mismatch between sample ID and file name for the 'QualityTrimmed' process, as well as a supposed missing ID in the manifest (which was actually present). Simply resuming the pipeline got rid of both errors. |
| 2022-07-06 | Setting up SPEAQeasy | I described how to configure SPEAQeasy for a particular dataset, and how to manage two separate runs of SPEAQeasy as part of a different git repository (requiring the use of submodules) |
| 2022-07-01 | Question about how 'mitoRate' is calculated in SPEAQeasy | I showed the documentation's description of 'mitoRate' and linked to the code where it's computed: https://github.com/LieberInstitute/SPEAQeasy/blob/bfe4e664281b52c5e239e372393a8aea36084e0d/scripts/create_count_objects.R#L521-L533 |
| 2022-06-29 | zellkonverter error and guidance using SpaGCN | I described the need to manually convert some spatialExperiment slots prior to conversion with zellkonverter, and that some data types are not supported. I pointed to my SpaGCN code and the lines specifically responsible for clustering + writing outputs |
| 2022-06-23 | pulling in external changes to a git repository | I described when 'git pull' can be "safely" used, and when 'git reset' might have to be used beforehand |
| 2022-06-21 | help installing 'jaffelab' | I described the use of 'remotes::install_github' for GitHub-based packages. We encountered a GitHub authentication error that was solved by running the R code 'Sys.unsetenv("GITHUB_PAT")' prior to the normal installation command. |
| 2022-05-05 | Guide to creating a module at JHPCE | I described the two JHPCE-based repositories we push to (https://github.com/LieberInstitute/jhpce_mod_source and https://github.com/LieberInstitute/jhpce_module_config), my usual installation approach for python-based GPU-utilizing software, and the contents of the lua-based config enabling a module to load. |
| 2022-04-29 | creating a nextflow pipeline and supporting docker | I clarified the usage of nextflow channels, described when docker integration is likely to be worthwhile, and answered other general questions about processing data with a nextflow-based workflow |
| 2022-04-01 | Using the "redstone" software | After identifying that 'redstone' was a precompiled binary for Linux, I described how to use 'wget' to download software like this, set execute permissions if necessary, and run at JHPCE. |
| 2022-03-25 | Input files for custom annotation with SPEAQeasy | I recommended some adjustments to a custom GTF and transcripts FASTA to solve an error seen in SPEAQeasy where transcripts and annotation were found to be incompatible. |
| 2022-03-17 | Follow-up on custom annotation with SPEAQeasy | An error occurred in a SPEAQeasy run, which I identified to be due to not providing all the required inputs (specifically the sites at which to perform variant calling) |
| 2022-03-16 | Adding lines to a GTF for use in SPEAQeasy with custom annotation | We both verified additional transcript annotation added to a GENCODE GTF looked good for use as input to SPEAQeasy |
| 2022-03-14 | Error message running SPEAQeasy | An error occurred in the counts step, which I discovered was a bug in some filename-matching code |
| 2022-03-09 | Setting up passwordless login | I described two-factor authentication vs. passwordless login via SSH keys, and gave tips to set up the latter. |
| 2022-03-09 | Using custom annotation with SPEAQeasy | I described how to add additional transcripts to the relevant FASTA file then use SPEAQeasy's custom annotation option to use the new FASTA with the other default annotation files. |
| 2022-03-04 | Using the caracol queue | I described how requesting 'caracol' is similar to requesting 'bluejay', but elaborated on additional complications, like contention for the same GPU and using CUDA_VISIBLE_DEVICES properly, including with array jobs |
| 2022-03-02 | Generating bigWigs with SPEAQeasy | I referred her to the '--coverage' option with SPEAQeasy, which unfortunately cannot be run alone, which might be useful for an already-processed dataset |
| 2022-02-07 | Debugging seg fault with tensorqtl module | We tried to discover the source of a seg fault that would occur when she imported tensorqtl in python with the tensorqtl module. Another user and I weren't able to replicate the issue. We later discovered that there were lines in her .bashrc that might've interfered with the module to produce the issue. |
| 2022-02-04 | Using tensorqtl with a GPU | I described how to qrsh/sub jobs with the GPU node, including how to automatically set up 'CUDA_VISIBLE_DEVICES' to avoid contention for resources, and how to use the tensorqtl module to ensure GPUs were used when importing pytorch |
| 2022-02-04 | X11 and SSH issues | After ensuring our apparent Rstudio set-ups on our windows machines matched, she still wasn't able to forward X11 while using Rstudio. Regarding a different issue, we discovered that a particular machine required additional lines in the '~/.ssh/config' to properly enable RSA keys. |
| 2022-01-21 | accessing the 'gpu' node at JHPCE correctly | I described how it's accessed as a queue, but some manual work is left to the user (checking which GPUs are open and setting 'CUDA_VISIBLE_DEVICES') |
| 2021-12-15 | creating a 'samples.manifest' and choosing trimming settings | I described how I normally deduce sample IDs from FASTQ filenames when creating a 'samples.manifest' file for SPEAQeasy, described the difference between '--trim_mode' settings that SPEAQeasy supports, and showed how to check what samples were trimmed. |
| 2021-11-17 | using 'list.files' in R | I described using regular expressions in R to match files in a directory. We encountered a weird case where 'list.files' seemed to return different numbers of matched files when run repeatedly. After ensuring we were in the right directory, the issue went away, but it was unclear what caused the original problem. |
| 2021-10-06 | help with git | I explained how I get out of the situation where files that are too big get accidentally committed (using 'git log', 'git reset --soft', and other details) |
| 2021-10-04 | debugging SPEAQeasy errors | We worked through an error message from the 'VariantsMerge' process, uncovering (arguably) a bug in SPEAQeasy, and I advised how to temporarily circumvent the problem. I also suggested a command for renaming a set of files that initially broke SPEAQeasy's assumptions. |
| 2021-09-22 | help with 'umask' and git | I talked about how Linux does not allow creation of files w/ execution permissions set, regardless of 'umask' settings such as in the '.bashrc'. I also explained how I use branching with git and other tips for managing a repo that others also develop on. |
| 2021-09-10 | merging FASTQ files automatically via SPEAQeasy | We downloaded a metadata table from SRA and parsed it through R to programatically create a "samples.manifest" file for use in SPEAQeasy, that merged samples that were each split into multiple FASTQ files. |
| 2021-09-03 | identifying SPEAQeasy error | SPEAQeasy would appear to run into "file not found" errors for just a handful of random samples in a large dataset. I eventually traced the error to a disk mounting issue on a particular compute node, which was resolved through bitsupport. |
| 2021-08-26 | resuming SPEAQeasy after an issue in the counts step | I mentioned that she encountered a bug that was fixed in a more recent version of SPEAQeasy, but suggested she manually add a line of code temporarily so that she could resume the run before updating |
| 2021-08-25 | downloading FASTQ files from SRA | I referred her to a script I had written in the past that contains the required commands and configuration  (with comments) for using the SRA toolkit |
| 2021-08-06 | Forming a data frame from data in multiple files | I showed a fairly standard method for concatenating tabular data from multiple files into a single matrix, and saving the resulting R object |
| 2021-07-14 | debugging SPEAQeasy errors | I described correct use of the "--input" argument, and we also found that many of the input FASTQs were empty, leading to a somewhat vague error message. |
| 2021-07-14 | getting SPEAQeasy running | In a series of email exchanges we diagnosed subtle errors resulting from bad FASTQ files and unintended options in the main script. Her feedback helped me improve some existing documentation. |
| 2021-07-13 | formatting a LaTeX document and bookdown website | I attempted some formatting tricks to eliminate unwanted whitespace but was ultimately unsuccessful. We suspected the LaTeX template required the whitespace to exist. We also tried to fix a bug with the header of a bookdown RMD not rendering as expected. It seemed that re-writing the header (without making any visible changes) fixed the issue, though we weren't sure of the source of the initial problem. |
| 2021-07-02 | Help indexing a possibly corrupt VCF file | We confirmed that an existing VCF was corrupt and found that tabix expected bgzip-compressed VCF input rather than compressed BCF input. |
| 2021-06-30 | Specifying output logs on SGE | I briefly mentioned the `-o` and `-e` arguments, and how several logs will generate in your home directory without those arguments and without `-cwd`, when "qsub"ing a job at JHPCE. |
| 2021-06-16 | addressing SPEAQeasy error | we talked about how to use the "--strand" option, the source of the error that was encountered |
| 2021-05-19 | Making a module | We went through the creation of an LIBD JHPCE module, covering the documentation process, lua syntax, and how to test a module before pushing. |
| 2021-05-19 | Configuring a parallel series of bash scripts | We adapted a series of bash scripts requiring parallel functionality for use at JHPCE. This involved correctly setting some path variables and requesting multiple cores through SGE for some scripts. |
| 2021-05-13 | Setting up a SPEAQeasy run | I described how I typically construct a "samples.manifest" file and configure SPEAQeasy for a particular experiment. |
| 2021-05-03 | Running SPEAQeasy- follow up | We observed an issue where log parsing in SPEAQeasy behaved differently for her and I due to a difference in default python version loaded at JHPCE. I fixed the hisat2/2.2.1 module to ensure consistent python version use. |
| 2021-04-28 | Constructing an array job from an existing sequential shell script | I showed how I typically produce an array job shell script for the situation where I have many samples of data to process the same way (SIMD). We talked about using a text file where each line contains one sample name, and referencing that in the array script. |
| 2021-04-26 | Running SPEAQeasy- follow up | We discussed how to handle strandness issues, and how different inferred strand patterns within a group of samples sequenced together can indicate problems with the input data. I described how to use the '--force_strand' option with SPEAQeasy |
| 2021-04-22 | Running SPEAQeasy | We went through cloning SPEAQeasy, creating a "samples.manifest" file with R, and other relevant details for running SPEAQeasy at JHPCE. I also helped him set up git at JHPCE |
| 2021-04-22 | Running SPEAQeasy- follow up | We troubleshooted strange errors from the main SPEAQeasy output, and saw that I was able to run the main script ("run_pipeline_jhpce.sh") but she encountered errors with an identical script. We suspected permissions issues in her working directory, which she emailed bitsupport about. |
| 2021-04-19 | Running SPEAQeasy | Although we encountered permissions issues, I showed how to create a "samples.manifest" file and configure SPEAQeasy for a particular set of samples. |
| 2021-04-12 | Running the old RNA-seq pipeline on some SRA data | I showed my typical process for creating a "samples.manifest" file for a given dataset, and how to submit a pipeline run. We continued to debug some minor issues over slack |
| 2021-04-07 | Nextflow overview for work with imputation pipeline | I covered various nextflow concepts, as well as my typical approach in creating and running a nextflow project at JHPCE |
| 2021-03-22 | Using an LIBD module | I described the need for the "module use" command and modifying the .bashrc to easily use LIBD modules |
| 2021-03-18 | Download SRA data and run SPEAQeasy | I fetched the SRA files, created a manifest and execution script for SPEAQeasy, but had an issue running "fastq-dump". I decided to hand off the request, partially complete. |
| 2021-03-10 | qSVA explanation and code review | He walked me through some code performing qSVA for a recent project, and I offered some tips involving code organization/ readibility. |
| 2021-03-03 | Advice for writing papers | We discussed how Sciwheel can be adapted for different journals, and provided general advice for getting started and formatting a paper for a particular journal. |
| 2021-03-02 | Clarification about how recent CMC data was processed with SPEAQeasy | I explained that SPEAQeasy was used for the recent hg38 processing, and an older version of a similar pipeline was used for the original hg19 processing. We discussed our new method for retrieving gene symbols ("org.*.eg.db" packages) and some general code advice. |
| 2021-03-02 | Our group's set-up and approach for writing papers with google docs, and managing citations | I went through the setup and example usage of Sciwheel and cross reference, and gave general advice (it's often easiest to start with the "Methods" section, etc) |
| 2021-02-25 | I need help in: downloading data from SRA to JHPCE, running SPEAQeasy to create rse object (one session will likely not be enough). | I explained how to use SPEAQeasy at JHPCE, and we tried an experimental method for downloading SRA data. The method didn't work, and we plan to meet again after I verify a more typical method works. |
| 2021-02-23 | I need help with setting up Mobaexterm. Unable to open new terminals and folder permission issues | I hadn't encountered the issue with new local terminals failing to open. I planned to follow up with better specific advice via email, and offer to explain this advice in a future DSGS. |
| 2021-01-06 | Correlation values from labeledHeatmap | [BioC Support website answer](https://support.bioconductor.org/p/p133591/#p133927) |
| 2020-12-09 | Help with importing HDF5 file | Used 'h5ls' command from shell to verify contents of file; eventually found we were looking at the wrong file (error message was cryptic about issue). https://jhu-genomics.slack.com/archives/CUYHWV7AA/p1607034309074800 |
| 2020-12-02 | Matching Variants Between Two VCF Objects | [BioC Support website answer](https://support.bioconductor.org/p/p133110/#p133319) |
| 2020-11-20 | ChipQC 'names' attribute [9] must be the same length as the vector [2]' | [BioC Support website answer](https://support.bioconductor.org/p/134569/#p133028) |
| 2020-11-11 | How does one modify a single value of a field in a seqinfo object? | [BioC Support website answer](https://support.bioconductor.org/p/134139/#p132829) |
| 2020-11-04 | Extracting Sequences from Fasta Files with Rsamtools | [BioC Support website answer](https://support.bioconductor.org/p/131600/#p132617) |
| 2020-11-02 | Help with SpaceRanger | NA |
| 2020-10-28 | Changing Row Names of MultiAssayExperiment Assay | [BioC Support website answer](https://support.bioconductor.org/p/p132406/#p132459) |
| 2020-10-28 | issue running spaceranger | initial issue seemed to do with the spaceranger command arguments; we are continuining to investigate possible module issues or insufficient code in the [blog post](http://research.libd.org/rstatsclub/2020/10/20/using-space-ranger-at-jhpce/) |
| 2020-10-26 | Help running speakeasy on MARCC and JHPCE please | NA |
| 2020-10-21 | Question: Cannot Install gmapR Bioconductor Package | [BioC Support website answer](https://support.bioconductor.org/p/131285/#134921) |

