# Abby

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2022-06-15 | Help troubleshooting shiny app that crashes on gene interactive tab | checked size of the spe object. checked that only has low res image files. check dim of colData. All sizes checkedout. Believe this to be a package problem. |
| 2022-05-27 | Help with BayesSpace clustering | Assessed results of BayesSpace joint clustering and suggested that Alice discard the spots with low library sizes to improve clustering. Offered to create small SPE object for her with just the for samples she will be doing long read sequencing on. |
| 2022-05-20 | Subsetting spe object for shiny app | created new script to subset spe object by removing some of the images.  updated app.R to load smaller spe object (half the size) and re-ran shiny app locally. Explained how to version control from local computer and fixed problem with version controlling large data file.  Still having same problem of not being able to view shiny app online |
| 2022-05-17 | VisiumIF DLPFC building spe | Tried to troubleshoot adding visium IF images to spe object |
| 2022-05-17 | OneDrive | Helped setup OneDrive folder for LC manuscript. Explained how to organize figure folders. |
| 2022-05-10 | Help Deploying Shiny App for DLPFC_IF | Helped fix error of shiny app not being able to find spe object. Helped sucessfully deploy app. |
| 2022-04-27 | help with html output of spaceranger | Helped explain the different parts of the html output of spaceranger and which fields are important to check for QC |
| 2022-04-08 | help with read10xVisiumWrapper() | I helped Heena address an error she was getting when trying to run read10XVisiumWrapper(). We noted an issue with the function and submitted an github issue to spatialLIBD. We got the function to work but only if you provide the path to the gtf file. Met for 1hr. |
| 2022-04-04 | help with clustering portion of th build_spe | modified code to work witth her dataset. did graph based clustering and plottiing. Explained benefits of clustering across samples. Advised her to do isoform calling on pseudobulked data for multiple samples. Met for 1hr. |
| 2022-03-27 | help with build_spe | Finished installing packages. Set up sample_info table. Walked her through the rest of the code. |
| 2022-03-18 | set up git repo for long read project | We set up a git repo and added code to be adapted to build an spe object from Alice's long read data. |
| 2022-03-17 | Assistance with analyzing spatial data | This was a preliminary meeting with Alice to decide where to begin with analyzing her spatial data. We decided to start by generating an spe object with her long read data. |

