# Arta

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2020-10-21 | copy number variation analysis (CNV) | [BioC Support website answer](https://support.bioconductor.org/p/134876/#134917) |
| 2020-11-12 | RDavid Error | [I recommended that they reach out to their forum board](https://support.bioconductor.org/p/p132558/#p132872) |
| 2020-11-23 | Ran Genome Studio, installed PLINK input plugin | [There is a plugin for Genome Studio by Illumina that allows users to output their imputed allele results as PLINK inputs](https://support.illumina.com/downloads/genomestudio-2-0-plug-ins.html) |
| 2020-12-03 | Inline formula throwing an error for interaction term | [RStudio Community self-answer](https://community.rstudio.com/t/recipes-package-cannot-create-interaction-term-in-step-interact/89860) |
| 2021-03-18 | Attempted SPEAQeasy installation on MacOS | Failed MacOS installation on Lieber MacBook, something about Java both being and also not being installed |
| 2021-04-20 | Running FUSION / TWAS | I gave Sreya a conceptual introduction to transcriptome imputation and sent her some resources to help her get started on FUSION / TWAS |
| 2021-04-28 | Setting up FUSION / TWAS for practice | I showed Sreya how to set up the S-TWAS directory that I adapted in the Zandi-Hyde bipolar project for her own adaptation. I also sent her some useful videos on how to set up GitHub with her JHPCE account and install an SFTP client for Ubuntu (I prefer Filezilla) |
| 2021-06-02 | Using GenomeStudio | Used GenomeStudio again to produce PLINK files |
| 2021-06-04 | Havent got my mds yet so making the meeting for Friday | N/A |
| 2021-06-15 | FUSION / TWAS Walkthrough | https://github.com/LieberInstitute/zandiHyde_bipolar_rnaseq/tree/master/dev_twas#bd-twas-workflow |
| 2021-06-21 | TWAS questions | cleared up some confusion about filter_snps.R |

