# Josh

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2022-03-02 | Work through qsvaR vignette together | Heena was encountering a simple error installing the package. We also spent time going through the vignette to give a conceptual overview of qsva. Her feedback will be helpful in making the vignette more accessible |
| 2021-07-28 | DNA genotyping overview | ibidem |
| 2021-06-16 | got mds score for the vcf she presented using plink | we discussed what a bfile is in plink and that made the process much easier. |
| 2021-06-10 | mds for vcfs | still working on this will touch base again, we are trying to obtain the mds plot for ancestry in the placental data. |
| 2021-06-05 | checking plots and data structure in clusterprofiler | the way we had run cluster profiler was generating lists in a way that the plot functions could not work with |
| 2021-06-01 | gene ontology for genesets | run clusterprofiler on a set of DE hits |
| 2021-05-14 | questions about processing genotype data | explained the process of using topmed imputation and later we will get the mds |
| 2021-03-26 | help doing a power analysis for RNA-seq data | sent him the scripts from andrew, wondering if I should make it into a function |
| 2020-10-28 | Learning Lexical Scoping Rules | NA |
| 2020-03-16 | get effect size for calcium imaging | reffered to package "effsize" should be efficient at easily doing this |

