# Leo

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2023-09-22 | snRNA-seq training | Resolved some questions related to https://github.com/ComunidadBioInfo/cdsb2021_scRNAseq and made two pull requests to fix typos. |
| 2023-09-22 | How to interpret terms on an interaction model | We went over the math derivations for interpreting beta1, beta2, and beta3 on an interaction model where X1 is a continuous variable, X2 is a discrete variable with 2 options and we model `Y ~ X1 * X2`. We also used `ExploreModelMatrix`. |
| 2023-09-21 | Guidance on expression heatmaps | I explained the benefits of centering and scaling and referred to both the short video on this topic https://youtu.be/c8ffeFVUzk8 as well as the material we developed for the CSHL 2023 course https://lcolladotor.github.io/cshl_rstats_genome_scale_2023/expression-heatmaps-with-complexheatmap.html. |
| 2023-09-14 | snRNA-seq training | Continued reviewing material from https://github.com/ComunidadBioInfo/cdsb2021_scRNAseq |
| 2023-09-13 | Social media ideas | Discussed a few ideas about LIBD and social media |
| 2023-08-21 | snRNA-seq training | Answered questions related to material at https://github.com/ComunidadBioInfo/cdsb2021_scRNAseq |
| 2023-08-18 | ranger_metrics | We talked about the first scripts in https://github.com/LieberInstitute/ranger_metrics |
| 2023-08-14 | Getting started with snRNA-seq | We talked about material at https://github.com/ComunidadBioInfo/cdsb2021_scRNAseq |
| 2023-08-10 | Introduction to what we do as a team and future plans | We talked about how I became an Investigator at LIBD, the overall type of work we do as a team, some of our main collaborations, and overall plans for applying for funding in the future. In particular, I highlighted how I want to train team members on how to write an NIH biosketch, though not all are going to be "key personnel". I sent a link to the DSgs, team meeting schedule, rstats club schedule, and our http://lcolladotor.github.io/talk/teamtldr2022/ summary from April 20, 2022. |
| 2023-07-27 | Guidance on reference data for deconvolution and snRNA-seq analysis | For deconvolution, we talked about finding an appropriate reference dataset and we talked about an expert we can contact to ask which dataset(s) might be the most relevant. For snRNA-seq data analysis, I mentioned OSCA (Orchestrating Single Cell Analysis with Bioconductor) and how Louise could help guide this person on our code based off OSCA through a series of DSgs sessions. |
| 2023-07-27 | Feedback on an R package + GO/KEGG enrichment analyses | We transferred https://github.com/LieberInstitute/qsvaRPkgDemo to the LieberInstitute account. I asked to include some citations for sources (like the image source) and some other small edits. For GO / KEGG enrichment with clusterProfiler I asked to not filter results (pvalueCutoff / qvalueCutoff parameters), so we can see more results prior to choosing which ones to plot. |
| 2023-07-26 | Evaluate a potential external contractor | We discussed the current status of the team, the project, what skills are required, boundaries in terms of time and who would be involved (and who wouldn't). We ended the session with me relaying a list of resources to check and read more carefully. Then in about 2 weeks we'll meet again to determine the next steps. |
| 2023-07-26 | How to best document what skills I can perform or need to learn | We made a Google sheet with columns such as `study_type`, `skill_name`, `learning_priority`, etc. I also worked on it after the DSgs session to help complete the current information. See [Slack](https://neuralplasticity.slack.com/archives/C04Q8MX99FY/p1690397027111449) for more details. |
| 2023-07-26 | Need help debugging iSEE app errors/warnings | We resolved this issue by making sure that the variable names for which they wanted to specify the correct colors were actually part of the colData(SE). See [Slack](https://jhu-genomics.slack.com/archives/C01KSLPCGAC/p1689858182290369) for the actual code links. I also asked them to make sure to use soft links / full paths instead of using setwd() for files outside the project + to keep all related files at JHPCE instead of on a laptop, to make it easier to rule out any sources of differences (aka for reproducibility purposes). |
| 2023-07-20 | Input on a course design | We discussed what would be the appropriate material for us to teach in a course. We will re-use some of our materials from https://github.com/lcolladotor/cshl_rstats_genome_scale_2023. |
| 2023-07-20 | Feedback on responding to reviewers | We went over the proposed response to reviewers, clarified some sentences, and requested co-authors to approve the response to the reviewers. |
| 2023-06-29 | How to make a project documentation website | We adapted code from https://github.com/LieberInstitute/spatialDLPFC/blob/main/code/update_website.R and https://github.com/LieberInstitute/spatialDLPFC/blob/main/README.Rmd in order to make the files at https://github.com/LieberInstitute/septum_lateral. See https://github.com/LieberInstitute/septum_lateral/commits/main from https://github.com/LieberInstitute/septum_lateral/commit/dda5822c0f74c1d143e317c211650a042c274f50 to https://github.com/LieberInstitute/septum_lateral/commit/230568af106ac9c75cd0045e76b762cdcc31cf4c as well as related commits on the `gh-pages` branch. |
| 2023-06-28 | clusterProfiler, set.seed, and BiocParallel questions | Summarized at https://jhu-genomics.slack.com/archives/C018ZDB8QLU/p1687982732826659. This involved explaining why we don't use as a background universe all genes in the annotation in gene ontology / KEGG pathway enrichment analyses. Instead, we use those that pass the expression filters and for which we computed differential expression statistics. |
| 2023-06-28 | Resolving a permissions issue | We resolved https://jhu-genomics.slack.com/archives/C02RG5VGL6R/p1687803353217199 at https://jhu-genomics.slack.com/archives/C02RG5VGL6R/p1687984850054149?thread_ts=1687803353.217199&cid=C02RG5VGL6R, which was due to a user incorrectly having a Linux group assigned to files at JHPCE when they are not part of the user group. Uploads through Cyberduck can trigger this. The solution is to run https://lcolladotor.github.io/bioc_team_ds/organizing-your-work.html#spatialteam-example again on a qrsh session. |
| 2023-06-27 | How to make dynamic error messages | We worked on qsvaR debugging an issue raised by Renee and Louise. We then improved the error messages on qsvaR as noted at https://github.com/LieberInstitute/qsvaR/commit/feb9a9e4f8a499baba76271de37ca39a9969f400. |
| 2023-06-23 | How to make a new Globus endpoint for a publication. | Using the septum lateral data, I trained Ryan on how to make this type of Globus endpoint, how to set up the right permissions, how to edit and update http://research.libd.org/globus/ (see [this](https://github.com/LieberInstitute/globus/blob/b10e0fb89c40489d23028e8ed3f7812cdea76a6b/index.Rmd#L57) for details), and how to document the Globus information on a manuscript. |
| 2023-06-22 | How to filter an SCE object prior to making an iSEE app | Using the lateral septum snRNA-seq data, I trained Heena on how to filter a SingleCellExperiment object to reduce the required memory from 7GB to less than 1GB in order to be able to deploy an iSEE app at shinyapps.io, whose computers have a maximum of 8 GB of RAM. See https://github.com/LieberInstitute/septum_lateral/commit/e6c5d0099e128b909dcf467d46b4f7f172820f98 and related commits. |
| 2023-06-21 | How to debug an R package function from a user's report | We worked with the script where Renee had noticed issues with qsvaR. We adapted it to work on qsvaR local updates through devtools::load_all(). We also resolved https://github.com/LieberInstitute/qsvaR/issues/29 and https://github.com/LieberInstitute/qsvaR/issues/28. |
| 2023-06-08 | Options for cell type specific eQTLs | Discussed how to best pseudobulk the data prior to doing this type of analysis. In particular, how to adapt https://github.com/LieberInstitute/spatialLIBD/blob/edc8b72505af097895dcbf35887df28da8122e3c/R/registration_pseudobulk.R#L135-L148 and related code, as well as plots to make such as boxplots of the min_ncells by cell type (without any filtering) and cutoffs found by `isOutlier()` (different cutoff for each cell type) + PCA plots colored by min_ncells. |
| 2023-06-08 | Overview of what we do as a team and outreach options | Discussed a few different areas of growth, including a change in direction related to our outreach activities. |
| 2023-03-13 | Updating spatialLIBD::read10xVisiumAnalysis | See https://jhu-genomics.slack.com/archives/C02TV4F1MCM/p1678716129409099 for more. Led to https://github.com/LieberInstitute/spatialLIBD/commit/97b852686515a271f4db3e185a9a9180a09a5db6 and related commits. spatialLIBD version 1.11.10 now supports spaceranger version 2023.0208.0 output files. |
| 2023-03-13 | Verify GitHub ssh key setup and team overview | We used https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection and also went over the JHPCE and R config files from the team website. We also talked about the DSgs and how it would be beneficial for Kinnary to meet 1 on 1 with all DSgs guides to build familiarity and make it easier to ask for help in the future. |
| 2023-03-10 | Debugging spatialLIBD::read10xVisiumAnalysis | See https://jhu-genomics.slack.com/archives/C02TV4F1MCM/p1678466684480179 for more details. Heena is working with spaceranger output files from 2 different versions, and in particular, version 2023.0208.0 (internal 10x Genomics version) changed their output files structure |
| 2023-03-09 | Overview on "R/Bioconductor-powered Team Data Science" | Described what we do, the DSgs system, potential for visitors at our team meeting, and research ideas. |
| 2023-03-02 | Help resolve JHPCE permission issues on the lifespan_hpc_spatial project | The solution involved asking BitSupport to login as a specific user and run https://lcolladotor.github.io/bioc_team_ds/organizing-your-work.html#spatialteam-example. Knowing the exact file paths that triggered the permission issues are important to help check with `ls -lh` and `nfs4_getfacl` under a `qrsh` session. |
| 2023-03-02 | Debug spaceranger 2023.0208.0 (likely an alpha for 2.0.1) with SpatialExperiment 1.8.0 | See the [Bioconductor Slack message](https://community-bioc.slack.com/archives/CR1BLV821/p1677783580326559) I wrote for more details. |
| 2023-03-02 | How to write a tweetorial | End result: https://twitter.com/HeenaDivecha/status/1631360771342098433 |
| 2023-03-02 | read10xVisium() in version 1.7.1 (and now 1.8.0) creates a dangerous silent error by mismatching tissue positions across multiple samples | See https://github.com/drighelli/SpatialExperiment/issues/135 and the pull request at https://github.com/drighelli/SpatialExperiment/pull/136 that resolves this issue. |
| 2023-02-28 | How to write a tweetorial | No public result just yet. |
| 2023-01-11 | Getting started with snRNA-seq | See [Slack notes](https://jhu-genomics.slack.com/archives/C0498763CUC/p1673451228034439) for further details. They involved https://github.com/LieberInstitute/template_project, https://drive.google.com/drive/folders/1cn5d-Ey7-kkMiex8-74qxvxtCQT6o72h, and other specific instructions for setting up a project. |
| 2022-11-01 | Introduction to LIBD and our team | https://lcolladotor.github.io/bioc_team_ds for my team website, https://docs.google.com/spreadsheets/d/1is8dZSd0FZ9Qi1Zvq1uRhm-P1McnJRd_zxdAfCRoMfA/edit?usp=sharing for the LIBD rstats club schedule, https://lcolladotor.github.io/bioc_team_ds/rbioconductor-data-science-bootcamps.html#bootcamp-source-materials could be of interest also, https://github.com/LieberInstitute/template_project for a template for organizing projects, learn about the DSgs https://lcolladotor.github.io/bioc_team_ds/data-science-guidance-sessions.html#.Y2GXx-zMJqs, https://rstudio.github.io/reticulate/ for using Python from R |
| 2022-09-29 | Overview on using GitHub for Matlab projects | We talked about https://github.com/LieberInstitute/template_project, https://hopstat.wordpress.com/2013/11/05/array-and-sequential-cluster-jobs/, http://research.libd.org/sgejobs/reference/job_single.html, https://github.com/LieberInstitute/template_project/blob/3987e7f307611b2bcf657d1aa6930e76c4cc2b9a/code/02_explore_data/01_ggpairs.sh#L7, https://lcolladotor.github.io/bioc_team_ds/organizing-your-work.html#.YzWxq-zMKX1, https://happygitwithr.com/, https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent. |
| 2022-09-23 | Introduction to DSgs, R, Bioconductor, JHPCE | LIBD rstats club schedule https://docs.google.com/spreadsheets/d/1is8dZSd0FZ9Qi1Zvq1uRhm-P1McnJRd_zxdAfCRoMfA/edit?usp=sharing. Bioconductor overview video https://youtu.be/c0Ch_sXiGDQ and related notes in case you want to skim them https://docs.google.com/document/d/1VZ4dOesHjbWhrvSIXO8Ne1Qk4ZdGEhAySNviZOHPqjI/edit?usp=sharing (we typically have this for each video entry). R and RStudio intro https://youtu.be/XTuJ8vGnzBU. Example vignette https://bioconductor.org/packages/release/data/experiment/vignettes/spatialLIBD/inst/doc/spatialLIBD.html from https://bioconductor.org/packages/spatialLIBD/. Data Science guidance sessions https://lcolladotor.github.io/bioc_team_ds/data-science-guidance-sessions.html#.Yy3s3ezMKX0. JHPCE new user request https://jhpce.jhu.edu/register/user/. Making your personal website with postcards https://youtu.be/9LUCZAx3SlU. Examples include https://lahuuki.github.io/ by Louise, https://jtleek.com/, http://aejaffe.com/. |
| 2022-09-06 | How to organize OneDrive files | Related to how we organize files for a publication. |
| 2022-08-24 | How can I interpret the y-axis from `plotExplanatoryVariables()`? | Density is related to the probability density function, see [wiki](https://en.wikipedia.org/wiki/Kernel_density_estimation for) more details. [This link](https://stats.stackexchange.com/questions/4220/can-a-probability-distribution-value-exceeding-1-be-ok) is also useful for understanding the y-axis in more detail. Violin plots are just density plots rotated 90 degrees and mirrored. They are compared against boxplots frequently, which while easier to understand, are not good for non-unimodal data. See [this link](https://mode.com/blog/violin-plot-examples/#:~:text=What%20is%20a%20violin%20plot%3F,the%20density%20of%20each%20variable) for more. I like `plotExplanatoryVariables()` because it's fast to run and gives a general idea of things. See [Figure 1b](https://bioconductor.org/packages/release/bioc/vignettes/variancePartition/inst/doc/variancePartition.pdf) from `variancePartition` for a violin plot of similar data. `variancePartition` can handle mixed effects models (random effects) and in that scenario is more precise, but will also take longer to compute. |
| 2022-08-17 | DE analysis introduction | Check [EnchancedVolcano](https://bioconductor.org/packages/devel/bioc/vignettes/EnhancedVolcano/inst/doc/EnhancedVolcano.html) which shows a quick DE guide and finishes with some Volcano plots, which can be good enough for a grant application. If you want to use limma, you could follow [the SPEAQeasy example](http://research.libd.org/SPEAQeasy-example/de_analysis_speaqeasy.html#16_Modeling) or [our DE bootcamp](http://research.libd.org/SPEAQeasy-example/bootcamp_intro#5_Day_3) a bit. Or dive deeper into [limma's documentation](http://bioconductor.org/packages/release/workflows/vignettes/RNAseq123/inst/doc/limmaWorkflow.html). |
| 2022-07-19 | Help with spatialLIBD colors setup | Note that `spe$var_colors` works for `spe$var` where the `var` part has to be the same in both variable names. Also `spe$var_colors` should be a named vector such that `unique(names(spe$var_colors))` matches `unique(spe$var)`. |
| 2022-07-15 | R, RStudio, git, SSH key setup | NA |
| 2022-07-12 | LIBD Data Science | NA |
| 2022-07-06 | Data science coordination | NA |
| 2022-06-03 | Tools and resources related to recount2 and recount3 | Talked about recount2, recount3, snaptron, snapcount, recount.bwtool, recount-brain, recount predictions, megadepth, the recount3 study explorer. I also sent them all the links to them, though you can find many of them at https://jhubiostatistics.shinyapps.io/recount/, https://jhubiostatistics.shinyapps.io/recount-brain/, and http://rna.recount.bio/. |
| 2022-05-27 | Debug `spatialLIBD::sig_genes_extract_all()`. | This had already been fixed, but Abby had an older version of spatialLIBD installed. We also went over some other steps needed to deploy an `spatialLIBD` app with pseudo-bulked data and modeling results. |
| 2022-05-27 | How to debug an R package code | Resulted in a fix for [this issue](https://github.com/LieberInstitute/spatialLIBD/issues/33#issuecomment-1137544893). |
| 2022-05-27 | Data science organization. | Brainstorming and planning session. |
| 2022-05-25 | MatLab questions. | Resolved via email. |
| 2022-05-20 | Brainomics meeting with collaborators | Review of statistical models as well as access to data |
| 2022-05-18 | Discussion on how to recruit members | Twitter, LinkedIn, jobRxiv |
| 2022-05-17 | BrainSeq Phase II development browser | Clarified what the data is showing and explained a bit the goals of the LIBD data portal that Geo Pertea is building. |
| 2022-05-06 | Career development | PhD programs and other options. |
| 2022-05-03 | How to make a tweetorial for a pre-print | See [this Twitter thread](https://twitter.com/lahuuki/status/1521581339903873024) for the result. |
| 2022-04-29 | File organization for a paper submission | Provided guidance on how to share images and how to organize supplementary files. Resulting in this [Figshare](https://doi.org/10.6084/m9.figshare.19729567.v1) zip file. |
| 2022-04-28 | In promptu meeting | NA |
| 2022-04-27 | Grant proposal feedback | NA |
| 2022-04-21 | CV feedback | NA |
| 2022-04-20 | Cover letter feedback | NA |
| 2022-04-15 | Debugged code from https://github.com/LieberInstitute/spatialLIBD/issues/33 | See https://github.com/LieberInstitute/spatialLIBD/issues/33#issuecomment-1100169012. |
| 2022-04-15 | Brainomics meeting with collaborators | Clarified a few questions about LIBD's SPEAQeasy RSE objects and a problem with some colData() that was missing, that we'll provide early next week. Send links to our deconvolution work with Louise A Huuki-Myers. |
| 2022-04-08 | How to delete large files from GitHub history | If the situation had been simple, that is, that the latest commit was the one that commited the large files, we could have used the solution described at http://lcolladotor.github.io/2020/03/18/you-just-committed-a-large-file-and-can-t-push-to-github/. Instead, we had to use https://rtyley.github.io/bfg-repo-cleaner/. |
| 2022-04-08 | macOS and JHPCE laptop set | JHPCE ssh keys (to avoid typing passwords when using qrsh), .Rprofile (both), .bashrc, .zshrc (laptop), iTerm2 (laptop), Textmate (laptop), remote port fowading for rmate, xquartz (laptop) installation and configuration. There are several LIBD rstats club videos on these topics already, but we just did all the setup fast. In particular, the .bashrc configuration was important to resolve a umask setting problem that was interfering with the permissions on the Visium IF AD project. |
| 2022-04-06 | Debugging JHPCE configuration files | See [this Slack thread](https://neuralplasticity.slack.com/archives/C010NFSQS48/p1649249130880349). Ultimately, this situation involved teaching Tony to share his code. |
| 2022-03-18 | The authenticity of host 'github.com' | I explained how the first time that you ssh into a new computer (which happens also with git pull/git push), you need to accept that the new host is authentic, which will then edit your ~/.ssh/known_hosts file. |
| 2022-03-16 | Plan how to make spatial registration R functions | This is challenging since it involves putting together code from multiple scripts/projects. We summarized the steps to do [on this GitHub issue thread](https://github.com/LieberInstitute/spatialLIBD/issues/33#issuecomment-1069493294). |
| 2022-03-15 | Clarifying what role deconvolution can play on LCM-seq | Louise and I discussed the [Dentate Gyrus, Jaffe at al, 2020](https://doi.org/10.1038/s41593-020-0604-z) paper which used LCM-seq, what deconvolution using Bisque can do, and what role it can play at different analytical stages. |
| 2022-03-11 | How to log in to JHU-controlled laptop | We had some trouble logging in because the WiFi wasn't working without logging in. We solved this by using an ethernet cable at LIBD (which is part of the JHU network). Once we logged in once, then we could use the WiFi. |
| 2022-03-04 | How to guide others learning DS | I described different strateguies for helping others navigate the world of data science. In particular, how weekly coding sessions can be really useful. |
| 2022-03-04 | "Megadepth usage to add a new annotation to hg38 file" | Created an R script that reads in the transcripts FASTA file from GENCODE and uses BSgenome from Bioconductor to edit it and save it as a larger .fasta.gz file. Nick Eagles helped us by pointing us to http://research.libd.org/SPEAQeasy/annotation.html#custom-annotation. |
| 2022-03-03 | How to build a cov_rse object using qSVA v1 | Linked to https://github.com/LieberInstitute/qsva_brain/blob/master/brainseq_phase2_qsv/quantify_top1000.R#L13, `/dcs04/lieber/lcolladotor/qSVA_LIBD3080/degradation_experiments/*/bed`, https://github.com/LieberInstitute/SPEAQeasy/blob/master/main.nf#L1774-L1855, https://github.com/LieberInstitute/RNAseq-pipeline/blob/master/sh/step5-coverage.sh, https://github.com/LieberInstitute/qsva_brain/blob/master/brainseq_phase2_qsv/quantify_top1000.R#L3-L50, https://github.com/LieberInstitute/qsva_brain/blob/master/brainseq_phase2_qsv/quantify_top1000.R#L5, https://github.com/LieberInstitute/recount.bwtool/blob/master/R/coverage_bwtool.R, https://github.com/LieberInstitute/megadepth/blob/master/R/read_coverage.R, https://github.com/LieberInstitute/recount.bwtool/blob/master/R/coverage_matrix_bwtool.R#L227-L253, https://github.com/CRG-Barcelona/bwtool/wiki#installation, http://lcolladotor.github.io/derfinder/reference/getRegionCoverage.html, and http://research.libd.org/qsvaR/. Andrew Jaffe linked `/users/ajaffe/Lieber/Projects/RNAseq/SzControl_DE_paper/rdas/degradation_mat_CMC_ribozero.rda`, `/users/ajaffe/Lieber/Projects/RNAseq/SzControl_DE_paper/run_de_analysis_CMC.R`, `/users/ajaffe/Lieber/Projects/RNAseq/SzControl_DE_paper/rdas/geneLevel_CMC_qSVsAndMod.rda` and `/users/ajaffe/Lieber/Projects/RNAseq/CMC/`. |
| 2022-03-03 | Debradation matrix for LIBD riboZ | Linked to https://github.com/LieberInstitute/qsvaR, http://research.libd.org/rstatsclub/2018/12/11/quality-surrogate-variable-analysis/#.YiFawRDMKX0, https://github.com/LieberInstitute/qsva_brain/blob/master/brainseq_phase2_qsv/quantify_top1000.R, https://github.com/LieberInstitute/qsva_brain/blob/master/brainseq_phase2_qsv/make_qSVs.R, https://github.com/LieberInstitute/qsva_brain/blob/master/brainseq_phase2_qsv/make_qSVs.R#L28. Made public the file `/dcl01/ajaffe/data/lab/qsva_brain/brainseq_phase2_qsv/rdas/degradation_rse_phase2_usingJoint_justFirst.rda` and other ones. See https://github.com/LieberInstitute/qsva_brain/commit/cba8fa5e886be9242dcbaae7854d1eed0f69cef5 for details. |
| 2022-02-24 | WGBS data analysis overview | Using BiocMAP http://research.libd.org/BiocMAP/ which Nick is finishing up, you could process the data and have R objects you could load and analyze. So, the data processing would be "easy" in a sense. Next, you might want to check the bsseq documentation https://bioconductor.org/packages/bsseq/ if you are interested in finding differentially methylated regions (DMRs) and in any case, because BiocMAP provides that type of R object as noted at http://research.libd.org/BiocMAP/outputs.html. https://jhubiostatistics.shinyapps.io/wgbsExprs/ and the companion paper is the last WGBS data analysis project I did myself with code at https://github.com/LieberInstitute/brain-epigenomics. Kira Perzel-Mandell, who worked with Shizhong, wrote https://github.com/LieberInstitute/wgbs_meqtl_analysis (link to paper there) and did other projects. If you are plotting methylation levels at some locations, then that's very direct. If you are trying to find DMRs, it can take a bit of time to get used to the large objects and the related complications (once you filter the data, it'll be more manageable). If you go into CpH instead of CpG, then memory constraints become harder to deal with. |
| 2022-02-18 | Ideas for possible future analyses | NA |
| 2022-02-16 | JHPCE array jobs and fasthplus | Related to JHPCE https://github.com/ntdyjack/fasthplus and http://research.libd.org/sgejobs/ |
| 2022-02-15 | snRNA-seq and deconvolution overview | Brainstormed several ideas related to deconvolution of bulk data as well as uses of snRNA-seq. Refered to OSCA https://bioconductor.org/books/release/OSCA/ at time. |
| 2021-12-06 | JHPCE file permissions and ACLs | Motivated /dcs04/lieber/lcolladotor/_jhpce_org_LIBD001/update_permissions_spatialteam.sh |
| 2021-10-20 | Transfering files between JHPCE disks | Explained some scripts such as /dcs04/lieber/lcolladotor/BrainSEQ_LIBD001/_jhpce_org |
| 2021-09-27 | Presentation preparation feedback | NA |
| 2021-08-06 | How to write a Twitter thread for a paper | We revised key features of Brenda Pardo's Twitter thread https://twitter.com/PardoBree/status/1388253938391175173?s=20 and some features that you would want your Twitter thread to have. |
| 2021-08-03 | Refining an abstract submission | We talked about all the details that go into writing an abstract for a conference. These details can take longer to complete than initially anticipated. |
| 2021-07-30 | Git branches | We revised how to make a new branch in Git working with https://github.com/lmweber/OSTA-book |
| 2021-07-28 | DNA genotyping overview | We discussed the current DNA genotype pipeline and potential changes others might want. |
| 2021-07-20 | Overview of the RNA-seq universe | From SPEAQeasy, to qSVA, deconvolution, TWAS, etc. It might be best to give a talk about all these topics to whoever is interested at LIBD since we know about all these pieces but others might not. |
| 2021-07-13 | Setting up a team at LIBD | We talked about https://lcolladotor.github.io/bioc_team_ds/ among other topics. |
| 2021-07-01 | How to set up a GitHub actions-powered website | This has changed over time. The most recent setup (as of 2021-08-06) is at https://github.com/lmweber/OSTA-book |
| 2021-06-29 | Planning session for getting up to speed with SpatialExperiment, spatialLIBD, here and ggplot2 | We talked about the set of videos and resources publicly available to get to learn about R, Bioconductor and these packages. It was a lot of information and I'm sure that we'll have more sessions later on to clarify questions as they arise. |
| 2021-06-29 | How to choose and add a licence to a GitHub repo | We talked about https://choosealicense.com/, https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository, https://creativecommons.org/choose/. |
| 2021-06-29 | Designing an MS-level class | We discussed the posibility of proposing a class that has a mix of biology lectures and some practical coding sessions. The coding sessions could be based after the CDSB 2021 mini courses series. |
| 2021-06-21 | Locating public data at JHPCE + bamtofastq workflow | We talked about the public data from Synapse and worked on locating some of it at JHPCE. I explained also how we have used bamtofastq when others don't share their FASTQ files. Basically, we use bamtofastq to reconstruct the original FASTQ files (you might have to append the unmapped FASTQs if they are provided by the original authors) and then run FASTQ-processing tools like our SPEAQeasy pipeline. |
| 2021-06-17 | How to transfer recount3 data | We met to figure out how to transfer the data for this collaboration, which ended up being quite tricky and involved using an SSH tunnel for rsync. Basically, a command like this one: `rsync -avzh -e 'ssh -o ProxyJump=user@server_somewhere_for_the_tunnel' *_files_of_interest user@final_server:/final_path/` |
| 2021-06-17 | How to get started with R | We discussed the different possible goals and ways to get to them and determined a path forward that relies on the rest of the DSgs system as well as existing LIBD rstats club videos to get started. It'll be supported by a meeting with Leo and others involved in the spatial transcriptomics projects from the R side. |
| 2021-06-17 | Brainstorming session on collaboration | I showed the initial version of the BrainSeq Phase II developmental expression explorer developed by Bill Ulrich and Aaron Goldman. We discussed other possibilities for the collaboration including helping set up SPEAQeasy in their servers. |
| 2021-06-02 | How to prepare for a LIBD seminar part 4 | We discussed the changes that we should make and the ones we shouldn't based on the feedback received from the practice talk with Keri's group. The feedback was excellent and very useful, however, we discussed which suggestions were maybe complicating the presentation too much and how to best incorporate them. |
| 2021-05-26 | How to prepare for a LIBD seminar part 3 | Similar to part 2. The presentation was looking very polished by this meeting! |
| 2021-05-24 | Grant application review | Helped review the grant application and revise the text. |
| 2021-05-21 | PredictDB weights | Further updates on asking for help with this complicated project. Suggested reaching out to other LIBD members who have tried running the software before. |
| 2021-05-20 | Help preparing a figure for a grant application | Discussed with Josh what figures we needed to prepare and how to generate them. This also involved base_size = 30 with ggplot2. Otherwise the font was too small to read it on the grant. |
| 2021-05-20 | How to prepare for a LIBD seminar part 2 | Now that a first major draft of the presentation was complete, we revised it and proposed some changes to it. Some of them involved remaking the figures using base_size = 20 or even 30 with ggplot2. For future work, it might be best to save the images with that font size from the beginning instead of having to update them later. |
| 2021-05-10 | Setting up covr using GitHub actions in an R package | We went over the details of the GitHub actions workflow created by biocthis, the parts that you need to run from biocthis::use_bioc_pkg_templates(), and resolving issues prompted by R CMD check + BiocCheck |
| 2021-05-07 | How to get started with computational biology | I gave an overview of the resources and materials we have created as well as the LIBD bootcamps that we have publicly available to help others get started with computational biology. This is likely the first of several meetings. |
| 2021-05-07 | How to insert a figure using the Oxford Bioinfomratics Overleaf LaTeX template | We spent a significant amount troubleshooting the problem here (nearly two hours?). In the end, using the insert image "here" LaTeX syntax resolved the problem. |
| 2021-05-06 | PredictDB weights | General advice on how to ask for help from open source projects |
| 2021-05-06 | How to prepare for a LIBD seminar | Initial planning session for the LIBD seminar. We talked about the different slides we planned to show and the flow of the presentation. We also scheduled 3 practice talks with different groups of people. |
| 2021-05-03 | TWAS prep | Overview of the TWAS pipeline |
| 2021-04-08 | General guidance on how to learn how to do differential expression analyses | Created a learning plan involving several team members that is now documented at a channel in JHU Genomics Slack. That way everyone can keep track of what others are teaching the person who asked the question, and we can have a common communication channel among everyone involved. Sessions include learning how to interact with JHPCE through RStudio, how to run SPEAQeasy, key R/Bioconductor packages (limma, SummarizedExperiment), and explore possible visualizations of interest. |
| 2021-03-29 | spatialLIBD support | Discussion about features that spatialLIBD could support to make it easier to use for newer data. |
| 2021-03-25 | Creating a documentation website using bookdown | Help with understanding [bookdown](https://bookdown.org/yihui/bookdown/) and ideas on how to organize a documentation website (chapters and information to consider). |
| 2021-03-25 | Clarification of LIBD support | Discussed the research project proposal and how we can help. |
| 2021-03-25 | General advice | General advice. Received feedback regarding file backups. |
| 2021-03-24 | Download SRA data and run SPEAQeasy | I identified that https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE154829 contains both miRNA and RNA-seq data. Using data from the SRA Run selector at https://trace.ncbi.nlm.nih.gov/Traces/study/?acc=SRP273137&o=acc_s%3Aa I was able to filter the data to the RNA-seq samples and subset the input samples.manifest file for SPEAQeasy. |
| 2021-03-24 | Explain the feasibility of an on-demand end user interface for DEG and eQTLs | To identify DEGs or eQTLs, the user has to choose what covariates to adjust for. Some studies might require more complicated models than others, as they might be from more than one brain region or present some batch effect. In addition, in newer projects we are considering adjusting for cell type fractions derived from deconvolution. Even if all the covariates were fixed across datasets, in DEGs we have typically adjusted for qSVs which are computed in a dataset-dependent fashion and in essence are PCs derived from degradation-associated genomic regions. Similarly, for eQTLs we adjust for expression PCs. In both we adjust for ancestry PCs. Computing PCs is input-dependent: you won't get the same values or PCs if you change which samples you are using. So, computing DEGs and eQTLs is not as simple as say a map-reduce problem where you compute the same thing for every input sample, then aggregate the per-sample results. We have steps that depend on the whole sample set. Then there's also steps for filtering expression features based on some minimum expression cutoffs. Plus, differences between say polyA and RiboZero data, which don't make sense to process together. For these reasons, I don't think that an on-demand computation pipeline is feasible based on a user selecting a set of input samples. Constructing RNA-seq objects (RangedSummarizedExperiment objects) as well as DNA genotyping VCF files based on a set of input samples is feasible and that's what others are building. After that, I think that it's best to adapt code we have (or even use newer tools) after carefully exploring the data. |
| 2021-03-11 | BSP2 eQTLs with a subset of SNPs | Adapted code and shared it at https://github.com/LieberInstitute/brainseq_phase2/tree/master/eQTL_full/subset_hancock |
| 2021-03-10 | How to write a small methods paper | Created GitHub issues at https://github.com/LieberInstitute/VisiumImgProcessing/issues |
| 2021-02-05 | BSP2 LIBD eQTLs request | NA |
| 2021-01-29 | Help determining what data is available and what can be used for an analysis | Use of galaxybrain for identifying samples with DNAm, DNA genotype and RNA-seq data |
| 2021-01-26 | Guidance on how to download data from a study in GEO | NA |
| 2021-01-14 | biocthis macOS GHA bug | [BioC Support website answer](https://support.bioconductor.org/p/p134069/#p134141) |
| 2021-01-11 | Questions related to accessing results from the DG paper by Andrew Jaffe | NA |
| 2020-11-25 | Accesing CMC RNA-seq data | Started PsychENCODE access request process |
| 2020-11-11 | Differences between recount2's "bp_length" and SPEAQeasy's "Length" | [Check Slack helpdesk channel](https://jhu-genomics.slack.com/archives/CUYHWV7AA/p1605123296024100) |
| 2020-11-11 | GitHub actions workflow issue with macOS on R-devel | [GitHub issue at biocthis](https://github.com/lcolladotor/biocthis/issues/15) |
| 2020-11-03 | Fixed two bugs on recount3 related to locate_url() for the BigWig files. | Resulted in recount3 versions 1.1.1 and 1.1.2 on bioc-devel (and 1.0.2 on bioc-release) |
| 2020-11-03 | Fixed a bug on biocthis for release branches | [GitHub issue at biocthis](https://github.com/lcolladotor/biocthis/issues/13) |
| 2020-11-03 | Issue with knitcitations | [GitHub issue at biocthis](https://github.com/lcolladotor/biocthis/issues/14) |
| 2020-10-30 | Issue with JHPCE file permissions | Explained the `chgrp` and `umask` commands plus `~/.bashrc` file configuration. I also mentioned why we don't use `chmod 777` at JHPCE. Details on [Slack](https://jhu-genomics.slack.com/archives/CR9NYA0BF/p1604086263148400?thread_ts=1603826219.094600&cid=CR9NYA0BF) (private channel). |
| 2020-10-30 | recount3 GTEx data access | [BioC Support website answer](https://support.bioconductor.org/p/p132487/#p132521) |
| 2020-10-28 | exceRpt pipeline counts | [BioC Support website answer](https://support.bioconductor.org/p/p132450/#p132464) |
| 2020-10-21 | Ballgown stattest | [BioC Support website answer](https://support.bioconductor.org/p/134914/#134915) |

