# Maddy

| Date | Help request | Notes |
| ---- | ------------ | ----- |
| 2022-09-09 | Code to threshold small sized nuclei from the NaCC visium images | NA |
| 2022-08-09 | VNS error | wrong input was given to the function |
| 2022-08-09 | Strategies to pick threshold for cell size in segmentations | NA |
| 2022-08-09 | open multichannel image in imagej | should select virtual stack option in bioformats reader when opening and multichannel image in imagej |
| 2022-08-08 | code to ectract x and y coordinates of randomnly slected inform tiles for PNN project | NA |
| 2022-07-28 | Pick randomn tiles for the PNN project | Explain how to pick randomn images to train PNN segmentation algorithm |
| 2022-07-19 | Extracting final output into table | code loops over the different file in the dataset and Marah was clearing it at the end of the loop every time which didnt let her save any data |
| 2022-06-23 | Adjusting thresholds for event detection using CaPTure | NA |
| 2022-06-10 | explain spaceranger output files | NA |
| 2022-05-17 | make modified tissue_positions_list from DLPFC IF samples for running spotsopcheck on mock PNN visium sample | NA |
| 2022-04-07 | Hey Maddy, I need something called "spot size"  on the 12 published DLPFC samples | spot size and scaling factor from json file. explained how each metric is associated to different version of the histology images. |
| 2022-04-07 | https://github.com/LieberInstitute/VistoSeg/issues/12 | Customized VistoSeg code to their histology images |
| 2022-04-06 | applying size threshold to vistoseg outputs to get rid of smaller regions that are not nuclei | NA |
| 2022-04-05 | directed the person to the VistoSeg website for steps to run VistoSeg | https://github.com/LieberInstitute/VistoSeg/issues/11 |
| 2022-03-22 | Help run trial shiny app deployment | Showed her app.R, deploy.R scripts and places where to edit, showed her how to navigate through the shinyapp portal to looks for logs when deploying the app. EXplained her few erros she ran through when deploying for the 1st time. |
| 2022-03-09 | VisiumIF loupe alignment | The contrast adjusted images on MAC::preview should be saved and uploaded back to JHPCE to run spaceranger. Spaceranger needs the exact same image that was used in the loupe alignment (even if it is changed from raw image on preview) |
| 2022-03-09 | Masking of blood vessels from PNN channel in PNN project | Explained how the image data can be manipulated when claudin5 channel and WFA channel are merged and then the blood vessels are segmented and masked. The correct way is to segment blood vessels from claudin channel and mask the segmented objects in WFA channel. |
| 2022-03-09 | How are InForm tiles arranged | The indices listed in the tiles's filename is the x,y coordinates of the starting topleft pixel of the given tile. These indices never start with [0,0] as these tiles are picked from the ROI in the phenochart and not the entire imaged area. Once stored in a directory these tiles are not arranged in chronological order. |
| 2022-02-25 | Data type change of image data when loading into Python | Used KJ's code from his rstats club presentation and described how the images shoukd be read using numpy array as uint32 but not floating https://colab.research.google.com/drive/1A4cavWcbgZF1PFQT87s5s_ATyZrN3IxL?usp=sharing |
| 2022-02-23 | contrast adjustment, intensity normalization, channel/gene description in PNN images | used HALO to show how contrast can be adjusted when changing min max values in the image |
| 2022-02-17 | rename files on JHPCE through command line | NA |
| 2022-02-16 | Provide comparison table for different metrics obtained from image meta data in MATLAB, for Visium IF workflow | NA |
| 2022-02-15 | Explain Tangram, scRNAseq count matrix, spe object | NA |
| 2022-02-14 | Explain the concept of Squidpy paper | https://www.nature.com/articles/s41592-021-01358-2 |
| 2022-02-11 | tiling and metadata changes in PNN project | NA |
| 2022-02-11 | explaination on Image metadata, bit depth | NA |
| 2022-02-10 | Need for rotation of visium array images and its spatial coordinnnate in spe object | NA |
| 2022-01-25 | VistoSegIF pipeline | explained the functions of this pipline as these are not yet documented |
| 2022-01-21 | Transfer data from JHPCE to Neural_Plasticity | command to use `rsync -avzh --progress userid@jhpce-transfer01:/source directory/ /destination directory/` |
| 2022-01-21 | Transfer data Neural_Plasticity to JHPCE | use rsync, prepend spaces in the paths with `\` to avoid issues |
| 2022-01-21 | JHPCE directory organization, repo linking, making commits | https://github.com/LieberInstitute/spatialDLPFC_SCZ/commit/43106c664883fd5df301e44cca35f2e8f2f289ad |
| 2022-01-21 | opening python, R, MATLAB console interactive session on JHPCE | explain how to use IDE's on local machine to edits scripts on JHPCE through cyberduck |
| 2022-01-20 | glitch in CAPTure tutorial about input data types to a function | https://github.com/LieberInstitute/CaPTure/issues/2 |
| 2021-12-09 | Removing smaller objects from VistoSeg segmentations | refining segmentations in matlab by applying size thresholds |
| 2021-12-08 | applying kmeans to CA3 mouse RNAscope data to obtain gene expression levels | Showed code how to scale data based on https://uc-r.github.io/kmeans_clustering and optimise kmeans for the present dataset |
| 2021-11-18 | running loupe browser for HPC images | Showed the steps on one sample HPC image and what outputs to save. |
| 2021-11-18 | countSpots from VistoSeg throwing errors for one DLPFC sample from round4 | While debugging, its seen that VistoSeg when splitting the raw image missed a part of fiducial frame for capture area D1 of that sample. This happens when the center of the visium slide does not align with the center of the image, which has ti be adjusted while imaging. This image when run through spaceranger provided negative coordinates for the missing fiducial frame part of the image, but MATLAB will not accept negative indices for a image, which was throwing errors when recontructing spot grind in countSpots function. |
| 2021-11-18 | Resolve issues with comments | Showed how to close issues on git with detailed comments of the final results |
| 2021-11-16 | batch processing - dotdotdot, on local machine | made custom Matlab script to batch process her 30 RNAscope images on her local machine |
| 2021-11-15 | error in transferring Visuim HPC data to JHPCE | The user directories were cleared during the software updates for LIBD server, emailed bill to create one for me and Heena to use rsync on Neural_Plasiticity. The filenames Heena used for 'source' in rync did not exist at the source directory which was throwing errors. |
| 2021-11-04 | using awk | to pick filename from textfile for a array job |
| 2021-10-14 | running spotspotcheck for SFN | NA |
| 2021-10-07 | doubts on VistoSeg | Explaination of why an index label M=3 was chosen for refineVNS in section 2.2. |
| 2021-09-20 | issues with regioprops function in dotdotdot | https://github.com/LieberInstitute/dotdotdot/issues/14 |
| 2021-09-14 | Fiducial frame enhancement for Visium IF images using preview on MAC | NA |
| 2021-09-14 | running Loupe browser for mannual alignment | NA |
| 2021-09-09 | Creating cyberduck bookmarks for JHPCE paths | NA |
| 2021-09-09 | writing shell script for countNuclei function in VistoSeg | NA |
| 2021-09-09 | Explaining Github issues, history and version control | NA |
| 2021-09-09 | Explaining SPE (Spatial Experiment) SCE (Single Cell Experiment) objects | https://files.slack.com/files-pri/T029RHR07-F024D7ELKC2/image_from_ios.jpg |
| 2021-09-09 | syntax error in shell script | used back quote instead of single quote when assigning string to variables |
| 2021-09-08 | CellProfiler H&E segmentations | We decided to run CellProfiler on a while capture area image of DLPFC sample to look at the segmentations as it was doing good job on the cropped regions of a DLPFC sample |
| 2021-09-07 | Trouble with implementing RNAscope function for humans | https://github.com/LieberInstitute/dotdotdot/issues/13 |
| 2021-09-02 | Error running VistoSeg::spospotcheck (Error in spotspotcheck>start (line 60)) | The H&E image that he was segmenting and the H&E image for which he gets the 'json' and 'csv' are not the same images or at least not the same resolution which is causing the error. |
| 2021-09-02 | Error while running rnascope_mouse - line 159 | https://github.com/LieberInstitute/dotdotdot/issues/12 |
| 2021-08-30 | parameter tuning for dotdotdot to split the nuclei clusters | NA |
| 2021-08-30 | improve lipofuscin masking in dotdotdot | NA |
| 2021-08-30 | dynamically name structures in matlab based on user inputs | used the command 'eval' |
| 2021-08-23 | Explain how to merge 2 data tables in R | NA |
| 2021-08-23 | Explain public keys and the authorized_keys file on JHPCE, removed duplicate public keys for the local machine to resolve ssh key login | NA |
| 2021-08-21 | resolving issues with multiple keys in the authorized_keys file | NA |
| 2021-08-18 | explanation of the methods and algorithm of a paper we are reviewing together | NA |
| 2021-08-11 | steps to resolve image segmentation of LC heated samples round 2 | NA |
| 2021-07-20 | Optimizing DAPI segmentation in dotdotdot | https://github.com/LieberInstitute/dotdotdot/issues/11 |
| 2021-07-15 | Explain how awk works | showed a example of how AWK extracts text lines from a text file |
| 2021-07-15 | Issues with SUFI | Explain how some scripts in SUFI run and the bash scripts to use in place of python scripts for batch processing |
| 2021-07-14 | Resolve errors produced by dotdotdot on SUFI output | Referred to Vijay's notes |
| 2021-07-14 | R Code to create list of files to be processed through VisiumLIBD | NA |
| 2021-07-14 | Setup aliases in bashrc | NA |
| 2021-07-09 | recreating spatstat plots with more features | used ggplot |
| 2021-07-09 | Helping understand errors from VisiumLIBD | NA |
| 2021-07-09 | Helping understand errors from VisiumLIBD | NA |
| 2021-06-24 | making a list of filenames in a specific folder and subfolder in R | used Sys.glob and write.table to write the list to txt file |
| 2021-06-24 | Rectified issues for batch running emma's RNAscope data | NA |
| 2021-06-24 | create shell script for batch running images on VisiumLIBD | NA |
| 2021-06-01 | troubleshoot SUFI output and figured it was not compatible with dotdotdot | NA |
| 2021-04-15 | running and trouble shooting VisiumIF image splitting code | NA |
| 2021-04-09 | Resolving issues with running dotdotdot on 20X RNAscope images | NA |
| 2021-04-09 | runnning Hiplex registration | NA |
| 2021-04-01 | creating logs for issues from running SUFI (spectral unmixing of fluorescent biological images) | explaination of nurolucida system, how number of cores and RAM matter for running SUFI |
| 2021-03-30 | steps to troubleshoot issues with stitched multi tile RNAscope images | NA |
| 2021-03-24 | running nucleiCount for spatial DLPFC samples | explaination of scale_factors.json, tissuepositions_list.csv from spaceranger and the spotspotcheck package |
| 2021-03-23 | extracting p-values from linear mixed effect model for Calcium imaging data | NA |
| 2021-03-17 | visium image segmentation | explaination of the functions VNS.m and refineVNS.m |
| 2021-03-17 | troubleshooting memory usage for VNS function from VisiumLIBD | when running VNS.m for several files on same matlab session the data from previous sessions is saved in matlab cache memory automatically. This will cause memory issues with subsequent runs, its important to clear variables after every run. |
| 2021-03-12 | split histology images into respective capture areas | ran her through an example, explained her the code on github repo (split.m is the main script) |
| 2021-03-12 | x-quartz installation | edited the config file for setting up x-quartz |
| 2021-03-06 | resolve figure generation error in human rnascope script from dotdotdot | fixed the github repo |
| 2021-03-05 | image analysis on QuPath | explore loading/saving/exporting options on Qupath |
| 2021-02-26 | data transfer from LIBD server to JHPCE | use rsync |
| 2021-02-26 | Submitting/debugging bash job for dotdotdot on cluster | Debugging through the input/output file in logs |
| 2021-02-19 | explaination of Owner/Group/Other permissions for files on JHPCe | running chmod |
| 2021-02-12 | download repository from github to cluster and run dotdotdot on cluster | Used Amy's rstats blogpost on git |
| 2021-02-05 | JHPCE ssh keypair set up | We got Heena's MAC registered for passwordless login to JHPCE |
| 2021-02-05 | dotdotdot parameter tuning for Ema's rat RNAscope data | NA |
| 2020-12-03 | run dotdotdot pipeline local computer and cluster | got through the Github vignettes thoroughly |
| 2020-12-03 | how to open matlab (GUI and command line) on JHPCE | NA |
| 2020-12-01 | how to connect to LIBD servers on windows and mac | NA |
| 2020-11-19 | data transfer from LIBD server to JHPCE | to use rsync or scp, you need to have user account created on LIBD server (Bill can help create it) |
| 2020-11-19 | download matlab on local computer through JHU software portal | NA |
| 2020-11-04 | 3D volume extraction in Matlab | https://www.mathworks.com/matlabcentral/answers/636365-how-can-i-measure-volume-from-a-3d-image?s_tid=srchtitle |
| 2020-10-28 | customize dotdotdot to his data | NA |

